# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /pilight

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /pilight

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"pilight\" \"webgui\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /pilight/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /pilight/CMakeFiles /pilight/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /pilight/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pilight

# Build rule for target.
pilight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight
.PHONY : pilight

# fast build rule for target.
pilight/fast:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/build
.PHONY : pilight/fast

#=============================================================================
# Target rules for targets named pilight-control

# Build rule for target.
pilight-control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-control
.PHONY : pilight-control

# fast build rule for target.
pilight-control/fast:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/build
.PHONY : pilight-control/fast

#=============================================================================
# Target rules for targets named pilight-daemon

# Build rule for target.
pilight-daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-daemon
.PHONY : pilight-daemon

# fast build rule for target.
pilight-daemon/fast:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/build
.PHONY : pilight-daemon/fast

#=============================================================================
# Target rules for targets named pilight-debug

# Build rule for target.
pilight-debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-debug
.PHONY : pilight-debug

# fast build rule for target.
pilight-debug/fast:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/build
.PHONY : pilight-debug/fast

#=============================================================================
# Target rules for targets named pilight-flash

# Build rule for target.
pilight-flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-flash
.PHONY : pilight-flash

# fast build rule for target.
pilight-flash/fast:
	$(MAKE) -f CMakeFiles/pilight-flash.dir/build.make CMakeFiles/pilight-flash.dir/build
.PHONY : pilight-flash/fast

#=============================================================================
# Target rules for targets named pilight-learn

# Build rule for target.
pilight-learn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-learn
.PHONY : pilight-learn

# fast build rule for target.
pilight-learn/fast:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/build
.PHONY : pilight-learn/fast

#=============================================================================
# Target rules for targets named pilight-raw

# Build rule for target.
pilight-raw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-raw
.PHONY : pilight-raw

# fast build rule for target.
pilight-raw/fast:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/build
.PHONY : pilight-raw/fast

#=============================================================================
# Target rules for targets named pilight-receive

# Build rule for target.
pilight-receive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-receive
.PHONY : pilight-receive

# fast build rule for target.
pilight-receive/fast:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/build
.PHONY : pilight-receive/fast

#=============================================================================
# Target rules for targets named pilight-send

# Build rule for target.
pilight-send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-send
.PHONY : pilight-send

# fast build rule for target.
pilight-send/fast:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/build
.PHONY : pilight-send/fast

#=============================================================================
# Target rules for targets named pilight-uuid

# Build rule for target.
pilight-uuid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-uuid
.PHONY : pilight-uuid

# fast build rule for target.
pilight-uuid/fast:
	$(MAKE) -f CMakeFiles/pilight-uuid.dir/build.make CMakeFiles/pilight-uuid.dir/build
.PHONY : pilight-uuid/fast

#=============================================================================
# Target rules for targets named pilight_shared

# Build rule for target.
pilight_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight_shared
.PHONY : pilight_shared

# fast build rule for target.
pilight_shared/fast:
	$(MAKE) -f CMakeFiles/pilight_shared.dir/build.make CMakeFiles/pilight_shared.dir/build
.PHONY : pilight_shared/fast

#=============================================================================
# Target rules for targets named pilight_static

# Build rule for target.
pilight_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight_static
.PHONY : pilight_static

# fast build rule for target.
pilight_static/fast:
	$(MAKE) -f CMakeFiles/pilight_static.dir/build.make CMakeFiles/pilight_static.dir/build
.PHONY : pilight_static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

control.o: control.c.o
.PHONY : control.o

# target to build an object file
control.c.o:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/control.c.o
.PHONY : control.c.o

control.i: control.c.i
.PHONY : control.i

# target to preprocess a source file
control.c.i:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/control.c.i
.PHONY : control.c.i

control.s: control.c.s
.PHONY : control.s

# target to generate assembly for a file
control.c.s:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/control.c.s
.PHONY : control.c.s

daemon.o: daemon.c.o
.PHONY : daemon.o

# target to build an object file
daemon.c.o:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/daemon.c.o
.PHONY : daemon.c.o

daemon.i: daemon.c.i
.PHONY : daemon.i

# target to preprocess a source file
daemon.c.i:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/daemon.c.i
.PHONY : daemon.c.i

daemon.s: daemon.c.s
.PHONY : daemon.s

# target to generate assembly for a file
daemon.c.s:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/daemon.c.s
.PHONY : daemon.c.s

debug.o: debug.c.o
.PHONY : debug.o

# target to build an object file
debug.c.o:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/debug.c.o
.PHONY : debug.c.o

debug.i: debug.c.i
.PHONY : debug.i

# target to preprocess a source file
debug.c.i:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/debug.c.i
.PHONY : debug.c.i

debug.s: debug.c.s
.PHONY : debug.s

# target to generate assembly for a file
debug.c.s:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/debug.c.s
.PHONY : debug.c.s

flash.o: flash.c.o
.PHONY : flash.o

# target to build an object file
flash.c.o:
	$(MAKE) -f CMakeFiles/pilight-flash.dir/build.make CMakeFiles/pilight-flash.dir/flash.c.o
.PHONY : flash.c.o

flash.i: flash.c.i
.PHONY : flash.i

# target to preprocess a source file
flash.c.i:
	$(MAKE) -f CMakeFiles/pilight-flash.dir/build.make CMakeFiles/pilight-flash.dir/flash.c.i
.PHONY : flash.c.i

flash.s: flash.c.s
.PHONY : flash.s

# target to generate assembly for a file
flash.c.s:
	$(MAKE) -f CMakeFiles/pilight-flash.dir/build.make CMakeFiles/pilight-flash.dir/flash.c.s
.PHONY : flash.c.s

learn.o: learn.c.o
.PHONY : learn.o

# target to build an object file
learn.c.o:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/learn.c.o
.PHONY : learn.c.o

learn.i: learn.c.i
.PHONY : learn.i

# target to preprocess a source file
learn.c.i:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/learn.c.i
.PHONY : learn.c.i

learn.s: learn.c.s
.PHONY : learn.s

# target to generate assembly for a file
learn.c.s:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/learn.c.s
.PHONY : learn.c.s

libs/avrdude/avr.o: libs/avrdude/avr.c.o
.PHONY : libs/avrdude/avr.o

# target to build an object file
libs/avrdude/avr.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avr.c.o
.PHONY : libs/avrdude/avr.c.o

libs/avrdude/avr.i: libs/avrdude/avr.c.i
.PHONY : libs/avrdude/avr.i

# target to preprocess a source file
libs/avrdude/avr.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avr.c.i
.PHONY : libs/avrdude/avr.c.i

libs/avrdude/avr.s: libs/avrdude/avr.c.s
.PHONY : libs/avrdude/avr.s

# target to generate assembly for a file
libs/avrdude/avr.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avr.c.s
.PHONY : libs/avrdude/avr.c.s

libs/avrdude/avrbitbang.o: libs/avrdude/avrbitbang.c.o
.PHONY : libs/avrdude/avrbitbang.o

# target to build an object file
libs/avrdude/avrbitbang.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrbitbang.c.o
.PHONY : libs/avrdude/avrbitbang.c.o

libs/avrdude/avrbitbang.i: libs/avrdude/avrbitbang.c.i
.PHONY : libs/avrdude/avrbitbang.i

# target to preprocess a source file
libs/avrdude/avrbitbang.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrbitbang.c.i
.PHONY : libs/avrdude/avrbitbang.c.i

libs/avrdude/avrbitbang.s: libs/avrdude/avrbitbang.c.s
.PHONY : libs/avrdude/avrbitbang.s

# target to generate assembly for a file
libs/avrdude/avrbitbang.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrbitbang.c.s
.PHONY : libs/avrdude/avrbitbang.c.s

libs/avrdude/avrconfig.o: libs/avrdude/avrconfig.c.o
.PHONY : libs/avrdude/avrconfig.o

# target to build an object file
libs/avrdude/avrconfig.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrconfig.c.o
.PHONY : libs/avrdude/avrconfig.c.o

libs/avrdude/avrconfig.i: libs/avrdude/avrconfig.c.i
.PHONY : libs/avrdude/avrconfig.i

# target to preprocess a source file
libs/avrdude/avrconfig.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrconfig.c.i
.PHONY : libs/avrdude/avrconfig.c.i

libs/avrdude/avrconfig.s: libs/avrdude/avrconfig.c.s
.PHONY : libs/avrdude/avrconfig.s

# target to generate assembly for a file
libs/avrdude/avrconfig.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrconfig.c.s
.PHONY : libs/avrdude/avrconfig.c.s

libs/avrdude/avrgpio.o: libs/avrdude/avrgpio.c.o
.PHONY : libs/avrdude/avrgpio.o

# target to build an object file
libs/avrdude/avrgpio.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrgpio.c.o
.PHONY : libs/avrdude/avrgpio.c.o

libs/avrdude/avrgpio.i: libs/avrdude/avrgpio.c.i
.PHONY : libs/avrdude/avrgpio.i

# target to preprocess a source file
libs/avrdude/avrgpio.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrgpio.c.i
.PHONY : libs/avrdude/avrgpio.c.i

libs/avrdude/avrgpio.s: libs/avrdude/avrgpio.c.s
.PHONY : libs/avrdude/avrgpio.s

# target to generate assembly for a file
libs/avrdude/avrgpio.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrgpio.c.s
.PHONY : libs/avrdude/avrgpio.c.s

libs/avrdude/avrpart.o: libs/avrdude/avrpart.c.o
.PHONY : libs/avrdude/avrpart.o

# target to build an object file
libs/avrdude/avrpart.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrpart.c.o
.PHONY : libs/avrdude/avrpart.c.o

libs/avrdude/avrpart.i: libs/avrdude/avrpart.c.i
.PHONY : libs/avrdude/avrpart.i

# target to preprocess a source file
libs/avrdude/avrpart.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrpart.c.i
.PHONY : libs/avrdude/avrpart.c.i

libs/avrdude/avrpart.s: libs/avrdude/avrpart.c.s
.PHONY : libs/avrdude/avrpart.s

# target to generate assembly for a file
libs/avrdude/avrpart.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrpart.c.s
.PHONY : libs/avrdude/avrpart.c.s

libs/avrdude/avrupd.o: libs/avrdude/avrupd.c.o
.PHONY : libs/avrdude/avrupd.o

# target to build an object file
libs/avrdude/avrupd.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrupd.c.o
.PHONY : libs/avrdude/avrupd.c.o

libs/avrdude/avrupd.i: libs/avrdude/avrupd.c.i
.PHONY : libs/avrdude/avrupd.i

# target to preprocess a source file
libs/avrdude/avrupd.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrupd.c.i
.PHONY : libs/avrdude/avrupd.c.i

libs/avrdude/avrupd.s: libs/avrdude/avrupd.c.s
.PHONY : libs/avrdude/avrupd.s

# target to generate assembly for a file
libs/avrdude/avrupd.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/avrupd.c.s
.PHONY : libs/avrdude/avrupd.c.s

libs/avrdude/fileio.o: libs/avrdude/fileio.c.o
.PHONY : libs/avrdude/fileio.o

# target to build an object file
libs/avrdude/fileio.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/fileio.c.o
.PHONY : libs/avrdude/fileio.c.o

libs/avrdude/fileio.i: libs/avrdude/fileio.c.i
.PHONY : libs/avrdude/fileio.i

# target to preprocess a source file
libs/avrdude/fileio.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/fileio.c.i
.PHONY : libs/avrdude/fileio.c.i

libs/avrdude/fileio.s: libs/avrdude/fileio.c.s
.PHONY : libs/avrdude/fileio.s

# target to generate assembly for a file
libs/avrdude/fileio.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/fileio.c.s
.PHONY : libs/avrdude/fileio.c.s

libs/avrdude/pgm.o: libs/avrdude/pgm.c.o
.PHONY : libs/avrdude/pgm.o

# target to build an object file
libs/avrdude/pgm.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/pgm.c.o
.PHONY : libs/avrdude/pgm.c.o

libs/avrdude/pgm.i: libs/avrdude/pgm.c.i
.PHONY : libs/avrdude/pgm.i

# target to preprocess a source file
libs/avrdude/pgm.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/pgm.c.i
.PHONY : libs/avrdude/pgm.c.i

libs/avrdude/pgm.s: libs/avrdude/pgm.c.s
.PHONY : libs/avrdude/pgm.s

# target to generate assembly for a file
libs/avrdude/pgm.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/pgm.c.s
.PHONY : libs/avrdude/pgm.c.s

libs/avrdude/safemode.o: libs/avrdude/safemode.c.o
.PHONY : libs/avrdude/safemode.o

# target to build an object file
libs/avrdude/safemode.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/safemode.c.o
.PHONY : libs/avrdude/safemode.c.o

libs/avrdude/safemode.i: libs/avrdude/safemode.c.i
.PHONY : libs/avrdude/safemode.i

# target to preprocess a source file
libs/avrdude/safemode.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/safemode.c.i
.PHONY : libs/avrdude/safemode.c.i

libs/avrdude/safemode.s: libs/avrdude/safemode.c.s
.PHONY : libs/avrdude/safemode.s

# target to generate assembly for a file
libs/avrdude/safemode.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/avrdude/safemode.c.s
.PHONY : libs/avrdude/safemode.c.s

libs/hardware/433gpio.o: libs/hardware/433gpio.c.o
.PHONY : libs/hardware/433gpio.o

# target to build an object file
libs/hardware/433gpio.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433gpio.c.o
.PHONY : libs/hardware/433gpio.c.o

libs/hardware/433gpio.i: libs/hardware/433gpio.c.i
.PHONY : libs/hardware/433gpio.i

# target to preprocess a source file
libs/hardware/433gpio.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433gpio.c.i
.PHONY : libs/hardware/433gpio.c.i

libs/hardware/433gpio.s: libs/hardware/433gpio.c.s
.PHONY : libs/hardware/433gpio.s

# target to generate assembly for a file
libs/hardware/433gpio.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433gpio.c.s
.PHONY : libs/hardware/433gpio.c.s

libs/hardware/433lirc.o: libs/hardware/433lirc.c.o
.PHONY : libs/hardware/433lirc.o

# target to build an object file
libs/hardware/433lirc.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433lirc.c.o
.PHONY : libs/hardware/433lirc.c.o

libs/hardware/433lirc.i: libs/hardware/433lirc.c.i
.PHONY : libs/hardware/433lirc.i

# target to preprocess a source file
libs/hardware/433lirc.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433lirc.c.i
.PHONY : libs/hardware/433lirc.c.i

libs/hardware/433lirc.s: libs/hardware/433lirc.c.s
.PHONY : libs/hardware/433lirc.s

# target to generate assembly for a file
libs/hardware/433lirc.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433lirc.c.s
.PHONY : libs/hardware/433lirc.c.s

libs/hardware/433pilight.o: libs/hardware/433pilight.c.o
.PHONY : libs/hardware/433pilight.o

# target to build an object file
libs/hardware/433pilight.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433pilight.c.o
.PHONY : libs/hardware/433pilight.c.o

libs/hardware/433pilight.i: libs/hardware/433pilight.c.i
.PHONY : libs/hardware/433pilight.i

# target to preprocess a source file
libs/hardware/433pilight.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433pilight.c.i
.PHONY : libs/hardware/433pilight.c.i

libs/hardware/433pilight.s: libs/hardware/433pilight.c.s
.PHONY : libs/hardware/433pilight.s

# target to generate assembly for a file
libs/hardware/433pilight.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/433pilight.c.s
.PHONY : libs/hardware/433pilight.c.s

libs/hardware/none.o: libs/hardware/none.c.o
.PHONY : libs/hardware/none.o

# target to build an object file
libs/hardware/none.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/none.c.o
.PHONY : libs/hardware/none.c.o

libs/hardware/none.i: libs/hardware/none.c.i
.PHONY : libs/hardware/none.i

# target to preprocess a source file
libs/hardware/none.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/none.c.i
.PHONY : libs/hardware/none.c.i

libs/hardware/none.s: libs/hardware/none.c.s
.PHONY : libs/hardware/none.s

# target to generate assembly for a file
libs/hardware/none.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardware/none.c.s
.PHONY : libs/hardware/none.c.s

libs/pilight/binary.o: libs/pilight/binary.c.o
.PHONY : libs/pilight/binary.o

# target to build an object file
libs/pilight/binary.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/binary.c.o
.PHONY : libs/pilight/binary.c.o

libs/pilight/binary.i: libs/pilight/binary.c.i
.PHONY : libs/pilight/binary.i

# target to preprocess a source file
libs/pilight/binary.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/binary.c.i
.PHONY : libs/pilight/binary.c.i

libs/pilight/binary.s: libs/pilight/binary.c.s
.PHONY : libs/pilight/binary.s

# target to generate assembly for a file
libs/pilight/binary.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/binary.c.s
.PHONY : libs/pilight/binary.c.s

libs/pilight/common.o: libs/pilight/common.c.o
.PHONY : libs/pilight/common.o

# target to build an object file
libs/pilight/common.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/common.c.o
.PHONY : libs/pilight/common.c.o

libs/pilight/common.i: libs/pilight/common.c.i
.PHONY : libs/pilight/common.i

# target to preprocess a source file
libs/pilight/common.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/common.c.i
.PHONY : libs/pilight/common.c.i

libs/pilight/common.s: libs/pilight/common.c.s
.PHONY : libs/pilight/common.s

# target to generate assembly for a file
libs/pilight/common.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/common.c.s
.PHONY : libs/pilight/common.c.s

libs/pilight/config.o: libs/pilight/config.c.o
.PHONY : libs/pilight/config.o

# target to build an object file
libs/pilight/config.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/config.c.o
.PHONY : libs/pilight/config.c.o

libs/pilight/config.i: libs/pilight/config.c.i
.PHONY : libs/pilight/config.i

# target to preprocess a source file
libs/pilight/config.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/config.c.i
.PHONY : libs/pilight/config.c.i

libs/pilight/config.s: libs/pilight/config.c.s
.PHONY : libs/pilight/config.s

# target to generate assembly for a file
libs/pilight/config.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/config.c.s
.PHONY : libs/pilight/config.c.s

libs/pilight/datetime.o: libs/pilight/datetime.c.o
.PHONY : libs/pilight/datetime.o

# target to build an object file
libs/pilight/datetime.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/datetime.c.o
.PHONY : libs/pilight/datetime.c.o

libs/pilight/datetime.i: libs/pilight/datetime.c.i
.PHONY : libs/pilight/datetime.i

# target to preprocess a source file
libs/pilight/datetime.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/datetime.c.i
.PHONY : libs/pilight/datetime.c.i

libs/pilight/datetime.s: libs/pilight/datetime.c.s
.PHONY : libs/pilight/datetime.s

# target to generate assembly for a file
libs/pilight/datetime.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/datetime.c.s
.PHONY : libs/pilight/datetime.c.s

libs/pilight/dso.o: libs/pilight/dso.c.o
.PHONY : libs/pilight/dso.o

# target to build an object file
libs/pilight/dso.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/dso.c.o
.PHONY : libs/pilight/dso.c.o

libs/pilight/dso.i: libs/pilight/dso.c.i
.PHONY : libs/pilight/dso.i

# target to preprocess a source file
libs/pilight/dso.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/dso.c.i
.PHONY : libs/pilight/dso.c.i

libs/pilight/dso.s: libs/pilight/dso.c.s
.PHONY : libs/pilight/dso.s

# target to generate assembly for a file
libs/pilight/dso.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/dso.c.s
.PHONY : libs/pilight/dso.c.s

libs/pilight/fcache.o: libs/pilight/fcache.c.o
.PHONY : libs/pilight/fcache.o

# target to build an object file
libs/pilight/fcache.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/fcache.c.o
.PHONY : libs/pilight/fcache.c.o

libs/pilight/fcache.i: libs/pilight/fcache.c.i
.PHONY : libs/pilight/fcache.i

# target to preprocess a source file
libs/pilight/fcache.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/fcache.c.i
.PHONY : libs/pilight/fcache.c.i

libs/pilight/fcache.s: libs/pilight/fcache.c.s
.PHONY : libs/pilight/fcache.s

# target to generate assembly for a file
libs/pilight/fcache.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/fcache.c.s
.PHONY : libs/pilight/fcache.c.s

libs/pilight/firmware.o: libs/pilight/firmware.c.o
.PHONY : libs/pilight/firmware.o

# target to build an object file
libs/pilight/firmware.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/firmware.c.o
.PHONY : libs/pilight/firmware.c.o

libs/pilight/firmware.i: libs/pilight/firmware.c.i
.PHONY : libs/pilight/firmware.i

# target to preprocess a source file
libs/pilight/firmware.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/firmware.c.i
.PHONY : libs/pilight/firmware.c.i

libs/pilight/firmware.s: libs/pilight/firmware.c.s
.PHONY : libs/pilight/firmware.s

# target to generate assembly for a file
libs/pilight/firmware.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/firmware.c.s
.PHONY : libs/pilight/firmware.c.s

libs/pilight/gc.o: libs/pilight/gc.c.o
.PHONY : libs/pilight/gc.o

# target to build an object file
libs/pilight/gc.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/gc.c.o
.PHONY : libs/pilight/gc.c.o

libs/pilight/gc.i: libs/pilight/gc.c.i
.PHONY : libs/pilight/gc.i

# target to preprocess a source file
libs/pilight/gc.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/gc.c.i
.PHONY : libs/pilight/gc.c.i

libs/pilight/gc.s: libs/pilight/gc.c.s
.PHONY : libs/pilight/gc.s

# target to generate assembly for a file
libs/pilight/gc.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/gc.c.s
.PHONY : libs/pilight/gc.c.s

libs/pilight/hardware.o: libs/pilight/hardware.c.o
.PHONY : libs/pilight/hardware.o

# target to build an object file
libs/pilight/hardware.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/hardware.c.o
.PHONY : libs/pilight/hardware.c.o

libs/pilight/hardware.i: libs/pilight/hardware.c.i
.PHONY : libs/pilight/hardware.i

# target to preprocess a source file
libs/pilight/hardware.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/hardware.c.i
.PHONY : libs/pilight/hardware.c.i

libs/pilight/hardware.s: libs/pilight/hardware.c.s
.PHONY : libs/pilight/hardware.s

# target to generate assembly for a file
libs/pilight/hardware.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/hardware.c.s
.PHONY : libs/pilight/hardware.c.s

libs/pilight/http_lib.o: libs/pilight/http_lib.c.o
.PHONY : libs/pilight/http_lib.o

# target to build an object file
libs/pilight/http_lib.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/http_lib.c.o
.PHONY : libs/pilight/http_lib.c.o

libs/pilight/http_lib.i: libs/pilight/http_lib.c.i
.PHONY : libs/pilight/http_lib.i

# target to preprocess a source file
libs/pilight/http_lib.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/http_lib.c.i
.PHONY : libs/pilight/http_lib.c.i

libs/pilight/http_lib.s: libs/pilight/http_lib.c.s
.PHONY : libs/pilight/http_lib.s

# target to generate assembly for a file
libs/pilight/http_lib.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/http_lib.c.s
.PHONY : libs/pilight/http_lib.c.s

libs/pilight/irq.o: libs/pilight/irq.c.o
.PHONY : libs/pilight/irq.o

# target to build an object file
libs/pilight/irq.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/irq.c.o
.PHONY : libs/pilight/irq.c.o

libs/pilight/irq.i: libs/pilight/irq.c.i
.PHONY : libs/pilight/irq.i

# target to preprocess a source file
libs/pilight/irq.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/irq.c.i
.PHONY : libs/pilight/irq.c.i

libs/pilight/irq.s: libs/pilight/irq.c.s
.PHONY : libs/pilight/irq.s

# target to generate assembly for a file
libs/pilight/irq.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/irq.c.s
.PHONY : libs/pilight/irq.c.s

libs/pilight/json.o: libs/pilight/json.c.o
.PHONY : libs/pilight/json.o

# target to build an object file
libs/pilight/json.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/json.c.o
.PHONY : libs/pilight/json.c.o

libs/pilight/json.i: libs/pilight/json.c.i
.PHONY : libs/pilight/json.i

# target to preprocess a source file
libs/pilight/json.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/json.c.i
.PHONY : libs/pilight/json.c.i

libs/pilight/json.s: libs/pilight/json.c.s
.PHONY : libs/pilight/json.s

# target to generate assembly for a file
libs/pilight/json.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/json.c.s
.PHONY : libs/pilight/json.c.s

libs/pilight/log.o: libs/pilight/log.c.o
.PHONY : libs/pilight/log.o

# target to build an object file
libs/pilight/log.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/log.c.o
.PHONY : libs/pilight/log.c.o

libs/pilight/log.i: libs/pilight/log.c.i
.PHONY : libs/pilight/log.i

# target to preprocess a source file
libs/pilight/log.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/log.c.i
.PHONY : libs/pilight/log.c.i

libs/pilight/log.s: libs/pilight/log.c.s
.PHONY : libs/pilight/log.s

# target to generate assembly for a file
libs/pilight/log.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/log.c.s
.PHONY : libs/pilight/log.c.s

libs/pilight/mongoose.o: libs/pilight/mongoose.c.o
.PHONY : libs/pilight/mongoose.o

# target to build an object file
libs/pilight/mongoose.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/mongoose.c.o
.PHONY : libs/pilight/mongoose.c.o

libs/pilight/mongoose.i: libs/pilight/mongoose.c.i
.PHONY : libs/pilight/mongoose.i

# target to preprocess a source file
libs/pilight/mongoose.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/mongoose.c.i
.PHONY : libs/pilight/mongoose.c.i

libs/pilight/mongoose.s: libs/pilight/mongoose.c.s
.PHONY : libs/pilight/mongoose.s

# target to generate assembly for a file
libs/pilight/mongoose.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/mongoose.c.s
.PHONY : libs/pilight/mongoose.c.s

libs/pilight/options.o: libs/pilight/options.c.o
.PHONY : libs/pilight/options.o

# target to build an object file
libs/pilight/options.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/options.c.o
.PHONY : libs/pilight/options.c.o

libs/pilight/options.i: libs/pilight/options.c.i
.PHONY : libs/pilight/options.i

# target to preprocess a source file
libs/pilight/options.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/options.c.i
.PHONY : libs/pilight/options.c.i

libs/pilight/options.s: libs/pilight/options.c.s
.PHONY : libs/pilight/options.s

# target to generate assembly for a file
libs/pilight/options.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/options.c.s
.PHONY : libs/pilight/options.c.s

libs/pilight/proc.o: libs/pilight/proc.c.o
.PHONY : libs/pilight/proc.o

# target to build an object file
libs/pilight/proc.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/proc.c.o
.PHONY : libs/pilight/proc.c.o

libs/pilight/proc.i: libs/pilight/proc.c.i
.PHONY : libs/pilight/proc.i

# target to preprocess a source file
libs/pilight/proc.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/proc.c.i
.PHONY : libs/pilight/proc.c.i

libs/pilight/proc.s: libs/pilight/proc.c.s
.PHONY : libs/pilight/proc.s

# target to generate assembly for a file
libs/pilight/proc.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/proc.c.s
.PHONY : libs/pilight/proc.c.s

libs/pilight/protocol.o: libs/pilight/protocol.c.o
.PHONY : libs/pilight/protocol.o

# target to build an object file
libs/pilight/protocol.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/protocol.c.o
.PHONY : libs/pilight/protocol.c.o

libs/pilight/protocol.i: libs/pilight/protocol.c.i
.PHONY : libs/pilight/protocol.i

# target to preprocess a source file
libs/pilight/protocol.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/protocol.c.i
.PHONY : libs/pilight/protocol.c.i

libs/pilight/protocol.s: libs/pilight/protocol.c.s
.PHONY : libs/pilight/protocol.s

# target to generate assembly for a file
libs/pilight/protocol.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/protocol.c.s
.PHONY : libs/pilight/protocol.c.s

libs/pilight/settings.o: libs/pilight/settings.c.o
.PHONY : libs/pilight/settings.o

# target to build an object file
libs/pilight/settings.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/settings.c.o
.PHONY : libs/pilight/settings.c.o

libs/pilight/settings.i: libs/pilight/settings.c.i
.PHONY : libs/pilight/settings.i

# target to preprocess a source file
libs/pilight/settings.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/settings.c.i
.PHONY : libs/pilight/settings.c.i

libs/pilight/settings.s: libs/pilight/settings.c.s
.PHONY : libs/pilight/settings.s

# target to generate assembly for a file
libs/pilight/settings.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/settings.c.s
.PHONY : libs/pilight/settings.c.s

libs/pilight/socket.o: libs/pilight/socket.c.o
.PHONY : libs/pilight/socket.o

# target to build an object file
libs/pilight/socket.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/socket.c.o
.PHONY : libs/pilight/socket.c.o

libs/pilight/socket.i: libs/pilight/socket.c.i
.PHONY : libs/pilight/socket.i

# target to preprocess a source file
libs/pilight/socket.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/socket.c.i
.PHONY : libs/pilight/socket.c.i

libs/pilight/socket.s: libs/pilight/socket.c.s
.PHONY : libs/pilight/socket.s

# target to generate assembly for a file
libs/pilight/socket.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/socket.c.s
.PHONY : libs/pilight/socket.c.s

libs/pilight/ssdp.o: libs/pilight/ssdp.c.o
.PHONY : libs/pilight/ssdp.o

# target to build an object file
libs/pilight/ssdp.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/ssdp.c.o
.PHONY : libs/pilight/ssdp.c.o

libs/pilight/ssdp.i: libs/pilight/ssdp.c.i
.PHONY : libs/pilight/ssdp.i

# target to preprocess a source file
libs/pilight/ssdp.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/ssdp.c.i
.PHONY : libs/pilight/ssdp.c.i

libs/pilight/ssdp.s: libs/pilight/ssdp.c.s
.PHONY : libs/pilight/ssdp.s

# target to generate assembly for a file
libs/pilight/ssdp.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/ssdp.c.s
.PHONY : libs/pilight/ssdp.c.s

libs/pilight/threads.o: libs/pilight/threads.c.o
.PHONY : libs/pilight/threads.o

# target to build an object file
libs/pilight/threads.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/threads.c.o
.PHONY : libs/pilight/threads.c.o

libs/pilight/threads.i: libs/pilight/threads.c.i
.PHONY : libs/pilight/threads.i

# target to preprocess a source file
libs/pilight/threads.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/threads.c.i
.PHONY : libs/pilight/threads.c.i

libs/pilight/threads.s: libs/pilight/threads.c.s
.PHONY : libs/pilight/threads.s

# target to generate assembly for a file
libs/pilight/threads.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/threads.c.s
.PHONY : libs/pilight/threads.c.s

libs/pilight/update.o: libs/pilight/update.c.o
.PHONY : libs/pilight/update.o

# target to build an object file
libs/pilight/update.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/update.c.o
.PHONY : libs/pilight/update.c.o

libs/pilight/update.i: libs/pilight/update.c.i
.PHONY : libs/pilight/update.i

# target to preprocess a source file
libs/pilight/update.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/update.c.i
.PHONY : libs/pilight/update.c.i

libs/pilight/update.s: libs/pilight/update.c.s
.PHONY : libs/pilight/update.s

# target to generate assembly for a file
libs/pilight/update.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/update.c.s
.PHONY : libs/pilight/update.c.s

libs/pilight/webserver.o: libs/pilight/webserver.c.o
.PHONY : libs/pilight/webserver.o

# target to build an object file
libs/pilight/webserver.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/webserver.c.o
.PHONY : libs/pilight/webserver.c.o

libs/pilight/webserver.i: libs/pilight/webserver.c.i
.PHONY : libs/pilight/webserver.i

# target to preprocess a source file
libs/pilight/webserver.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/webserver.c.i
.PHONY : libs/pilight/webserver.c.i

libs/pilight/webserver.s: libs/pilight/webserver.c.s
.PHONY : libs/pilight/webserver.s

# target to generate assembly for a file
libs/pilight/webserver.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/webserver.c.s
.PHONY : libs/pilight/webserver.c.s

libs/pilight/wiringPi.o: libs/pilight/wiringPi.c.o
.PHONY : libs/pilight/wiringPi.o

# target to build an object file
libs/pilight/wiringPi.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPi.c.o
.PHONY : libs/pilight/wiringPi.c.o

libs/pilight/wiringPi.i: libs/pilight/wiringPi.c.i
.PHONY : libs/pilight/wiringPi.i

# target to preprocess a source file
libs/pilight/wiringPi.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPi.c.i
.PHONY : libs/pilight/wiringPi.c.i

libs/pilight/wiringPi.s: libs/pilight/wiringPi.c.s
.PHONY : libs/pilight/wiringPi.s

# target to generate assembly for a file
libs/pilight/wiringPi.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPi.c.s
.PHONY : libs/pilight/wiringPi.c.s

libs/pilight/wiringPiI2C.o: libs/pilight/wiringPiI2C.c.o
.PHONY : libs/pilight/wiringPiI2C.o

# target to build an object file
libs/pilight/wiringPiI2C.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPiI2C.c.o
.PHONY : libs/pilight/wiringPiI2C.c.o

libs/pilight/wiringPiI2C.i: libs/pilight/wiringPiI2C.c.i
.PHONY : libs/pilight/wiringPiI2C.i

# target to preprocess a source file
libs/pilight/wiringPiI2C.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPiI2C.c.i
.PHONY : libs/pilight/wiringPiI2C.c.i

libs/pilight/wiringPiI2C.s: libs/pilight/wiringPiI2C.c.s
.PHONY : libs/pilight/wiringPiI2C.s

# target to generate assembly for a file
libs/pilight/wiringPiI2C.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPiI2C.c.s
.PHONY : libs/pilight/wiringPiI2C.c.s

libs/protocols/arctech_switch_old.o: libs/protocols/arctech_switch_old.c.o
.PHONY : libs/protocols/arctech_switch_old.o

# target to build an object file
libs/protocols/arctech_switch_old.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_switch_old.c.o
.PHONY : libs/protocols/arctech_switch_old.c.o

libs/protocols/arctech_switch_old.i: libs/protocols/arctech_switch_old.c.i
.PHONY : libs/protocols/arctech_switch_old.i

# target to preprocess a source file
libs/protocols/arctech_switch_old.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_switch_old.c.i
.PHONY : libs/protocols/arctech_switch_old.c.i

libs/protocols/arctech_switch_old.s: libs/protocols/arctech_switch_old.c.s
.PHONY : libs/protocols/arctech_switch_old.s

# target to generate assembly for a file
libs/protocols/arctech_switch_old.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_switch_old.c.s
.PHONY : libs/protocols/arctech_switch_old.c.s

libs/protocols/datetime.o: libs/protocols/datetime.c.o
.PHONY : libs/protocols/datetime.o

# target to build an object file
libs/protocols/datetime.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/datetime.c.o
.PHONY : libs/protocols/datetime.c.o

libs/protocols/datetime.i: libs/protocols/datetime.c.i
.PHONY : libs/protocols/datetime.i

# target to preprocess a source file
libs/protocols/datetime.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/datetime.c.i
.PHONY : libs/protocols/datetime.c.i

libs/protocols/datetime.s: libs/protocols/datetime.c.s
.PHONY : libs/protocols/datetime.s

# target to generate assembly for a file
libs/protocols/datetime.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/datetime.c.s
.PHONY : libs/protocols/datetime.c.s

libs/protocols/generic_switch.o: libs/protocols/generic_switch.c.o
.PHONY : libs/protocols/generic_switch.o

# target to build an object file
libs/protocols/generic_switch.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_switch.c.o
.PHONY : libs/protocols/generic_switch.c.o

libs/protocols/generic_switch.i: libs/protocols/generic_switch.c.i
.PHONY : libs/protocols/generic_switch.i

# target to preprocess a source file
libs/protocols/generic_switch.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_switch.c.i
.PHONY : libs/protocols/generic_switch.c.i

libs/protocols/generic_switch.s: libs/protocols/generic_switch.c.s
.PHONY : libs/protocols/generic_switch.s

# target to generate assembly for a file
libs/protocols/generic_switch.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_switch.c.s
.PHONY : libs/protocols/generic_switch.c.s

libs/protocols/lirc.o: libs/protocols/lirc.c.o
.PHONY : libs/protocols/lirc.o

# target to build an object file
libs/protocols/lirc.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/lirc.c.o
.PHONY : libs/protocols/lirc.c.o

libs/protocols/lirc.i: libs/protocols/lirc.c.i
.PHONY : libs/protocols/lirc.i

# target to preprocess a source file
libs/protocols/lirc.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/lirc.c.i
.PHONY : libs/protocols/lirc.c.i

libs/protocols/lirc.s: libs/protocols/lirc.c.s
.PHONY : libs/protocols/lirc.s

# target to generate assembly for a file
libs/protocols/lirc.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/lirc.c.s
.PHONY : libs/protocols/lirc.c.s

libs/protocols/pilight_firmware_v2.o: libs/protocols/pilight_firmware_v2.c.o
.PHONY : libs/protocols/pilight_firmware_v2.o

# target to build an object file
libs/protocols/pilight_firmware_v2.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/pilight_firmware_v2.c.o
.PHONY : libs/protocols/pilight_firmware_v2.c.o

libs/protocols/pilight_firmware_v2.i: libs/protocols/pilight_firmware_v2.c.i
.PHONY : libs/protocols/pilight_firmware_v2.i

# target to preprocess a source file
libs/protocols/pilight_firmware_v2.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/pilight_firmware_v2.c.i
.PHONY : libs/protocols/pilight_firmware_v2.c.i

libs/protocols/pilight_firmware_v2.s: libs/protocols/pilight_firmware_v2.c.s
.PHONY : libs/protocols/pilight_firmware_v2.s

# target to generate assembly for a file
libs/protocols/pilight_firmware_v2.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/pilight_firmware_v2.c.s
.PHONY : libs/protocols/pilight_firmware_v2.c.s

libs/protocols/pilight_firmware_v3.o: libs/protocols/pilight_firmware_v3.c.o
.PHONY : libs/protocols/pilight_firmware_v3.o

# target to build an object file
libs/protocols/pilight_firmware_v3.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/pilight_firmware_v3.c.o
.PHONY : libs/protocols/pilight_firmware_v3.c.o

libs/protocols/pilight_firmware_v3.i: libs/protocols/pilight_firmware_v3.c.i
.PHONY : libs/protocols/pilight_firmware_v3.i

# target to preprocess a source file
libs/protocols/pilight_firmware_v3.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/pilight_firmware_v3.c.i
.PHONY : libs/protocols/pilight_firmware_v3.c.i

libs/protocols/pilight_firmware_v3.s: libs/protocols/pilight_firmware_v3.c.s
.PHONY : libs/protocols/pilight_firmware_v3.s

# target to generate assembly for a file
libs/protocols/pilight_firmware_v3.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/pilight_firmware_v3.c.s
.PHONY : libs/protocols/pilight_firmware_v3.c.s

libs/protocols/quigg_gt1000.o: libs/protocols/quigg_gt1000.c.o
.PHONY : libs/protocols/quigg_gt1000.o

# target to build an object file
libs/protocols/quigg_gt1000.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/quigg_gt1000.c.o
.PHONY : libs/protocols/quigg_gt1000.c.o

libs/protocols/quigg_gt1000.i: libs/protocols/quigg_gt1000.c.i
.PHONY : libs/protocols/quigg_gt1000.i

# target to preprocess a source file
libs/protocols/quigg_gt1000.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/quigg_gt1000.c.i
.PHONY : libs/protocols/quigg_gt1000.c.i

libs/protocols/quigg_gt1000.s: libs/protocols/quigg_gt1000.c.s
.PHONY : libs/protocols/quigg_gt1000.s

# target to generate assembly for a file
libs/protocols/quigg_gt1000.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/quigg_gt1000.c.s
.PHONY : libs/protocols/quigg_gt1000.c.s

libs/protocols/quigg_switch.o: libs/protocols/quigg_switch.c.o
.PHONY : libs/protocols/quigg_switch.o

# target to build an object file
libs/protocols/quigg_switch.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/quigg_switch.c.o
.PHONY : libs/protocols/quigg_switch.c.o

libs/protocols/quigg_switch.i: libs/protocols/quigg_switch.c.i
.PHONY : libs/protocols/quigg_switch.i

# target to preprocess a source file
libs/protocols/quigg_switch.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/quigg_switch.c.i
.PHONY : libs/protocols/quigg_switch.c.i

libs/protocols/quigg_switch.s: libs/protocols/quigg_switch.c.s
.PHONY : libs/protocols/quigg_switch.s

# target to generate assembly for a file
libs/protocols/quigg_switch.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/quigg_switch.c.s
.PHONY : libs/protocols/quigg_switch.c.s

libs/protocols/raw.o: libs/protocols/raw.c.o
.PHONY : libs/protocols/raw.o

# target to build an object file
libs/protocols/raw.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/raw.c.o
.PHONY : libs/protocols/raw.c.o

libs/protocols/raw.i: libs/protocols/raw.c.i
.PHONY : libs/protocols/raw.i

# target to preprocess a source file
libs/protocols/raw.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/raw.c.i
.PHONY : libs/protocols/raw.c.i

libs/protocols/raw.s: libs/protocols/raw.c.s
.PHONY : libs/protocols/raw.s

# target to generate assembly for a file
libs/protocols/raw.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/raw.c.s
.PHONY : libs/protocols/raw.c.s

libs/protocols/relay.o: libs/protocols/relay.c.o
.PHONY : libs/protocols/relay.o

# target to build an object file
libs/protocols/relay.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/relay.c.o
.PHONY : libs/protocols/relay.c.o

libs/protocols/relay.i: libs/protocols/relay.c.i
.PHONY : libs/protocols/relay.i

# target to preprocess a source file
libs/protocols/relay.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/relay.c.i
.PHONY : libs/protocols/relay.c.i

libs/protocols/relay.s: libs/protocols/relay.c.s
.PHONY : libs/protocols/relay.s

# target to generate assembly for a file
libs/protocols/relay.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/relay.c.s
.PHONY : libs/protocols/relay.c.s

libs/protocols/xbmc.o: libs/protocols/xbmc.c.o
.PHONY : libs/protocols/xbmc.o

# target to build an object file
libs/protocols/xbmc.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/xbmc.c.o
.PHONY : libs/protocols/xbmc.c.o

libs/protocols/xbmc.i: libs/protocols/xbmc.c.i
.PHONY : libs/protocols/xbmc.i

# target to preprocess a source file
libs/protocols/xbmc.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/xbmc.c.i
.PHONY : libs/protocols/xbmc.c.i

libs/protocols/xbmc.s: libs/protocols/xbmc.c.s
.PHONY : libs/protocols/xbmc.s

# target to generate assembly for a file
libs/protocols/xbmc.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/xbmc.c.s
.PHONY : libs/protocols/xbmc.c.s

raw.o: raw.c.o
.PHONY : raw.o

# target to build an object file
raw.c.o:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/raw.c.o
.PHONY : raw.c.o

raw.i: raw.c.i
.PHONY : raw.i

# target to preprocess a source file
raw.c.i:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/raw.c.i
.PHONY : raw.c.i

raw.s: raw.c.s
.PHONY : raw.s

# target to generate assembly for a file
raw.c.s:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/raw.c.s
.PHONY : raw.c.s

receive.o: receive.c.o
.PHONY : receive.o

# target to build an object file
receive.c.o:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/receive.c.o
.PHONY : receive.c.o

receive.i: receive.c.i
.PHONY : receive.i

# target to preprocess a source file
receive.c.i:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/receive.c.i
.PHONY : receive.c.i

receive.s: receive.c.s
.PHONY : receive.s

# target to generate assembly for a file
receive.c.s:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/receive.c.s
.PHONY : receive.c.s

send.o: send.c.o
.PHONY : send.o

# target to build an object file
send.c.o:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/send.c.o
.PHONY : send.c.o

send.i: send.c.i
.PHONY : send.i

# target to preprocess a source file
send.c.i:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/send.c.i
.PHONY : send.c.i

send.s: send.c.s
.PHONY : send.s

# target to generate assembly for a file
send.c.s:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/send.c.s
.PHONY : send.c.s

uuid.o: uuid.c.o
.PHONY : uuid.o

# target to build an object file
uuid.c.o:
	$(MAKE) -f CMakeFiles/pilight-uuid.dir/build.make CMakeFiles/pilight-uuid.dir/uuid.c.o
.PHONY : uuid.c.o

uuid.i: uuid.c.i
.PHONY : uuid.i

# target to preprocess a source file
uuid.c.i:
	$(MAKE) -f CMakeFiles/pilight-uuid.dir/build.make CMakeFiles/pilight-uuid.dir/uuid.c.i
.PHONY : uuid.c.i

uuid.s: uuid.c.s
.PHONY : uuid.s

# target to generate assembly for a file
uuid.c.s:
	$(MAKE) -f CMakeFiles/pilight-uuid.dir/build.make CMakeFiles/pilight-uuid.dir/uuid.c.s
.PHONY : uuid.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... pilight"
	@echo "... pilight-control"
	@echo "... pilight-daemon"
	@echo "... pilight-debug"
	@echo "... pilight-flash"
	@echo "... pilight-learn"
	@echo "... pilight-raw"
	@echo "... pilight-receive"
	@echo "... pilight-send"
	@echo "... pilight-uuid"
	@echo "... pilight_shared"
	@echo "... pilight_static"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... control.o"
	@echo "... control.i"
	@echo "... control.s"
	@echo "... daemon.o"
	@echo "... daemon.i"
	@echo "... daemon.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... flash.o"
	@echo "... flash.i"
	@echo "... flash.s"
	@echo "... learn.o"
	@echo "... learn.i"
	@echo "... learn.s"
	@echo "... libs/avrdude/avr.o"
	@echo "... libs/avrdude/avr.i"
	@echo "... libs/avrdude/avr.s"
	@echo "... libs/avrdude/avrbitbang.o"
	@echo "... libs/avrdude/avrbitbang.i"
	@echo "... libs/avrdude/avrbitbang.s"
	@echo "... libs/avrdude/avrconfig.o"
	@echo "... libs/avrdude/avrconfig.i"
	@echo "... libs/avrdude/avrconfig.s"
	@echo "... libs/avrdude/avrgpio.o"
	@echo "... libs/avrdude/avrgpio.i"
	@echo "... libs/avrdude/avrgpio.s"
	@echo "... libs/avrdude/avrpart.o"
	@echo "... libs/avrdude/avrpart.i"
	@echo "... libs/avrdude/avrpart.s"
	@echo "... libs/avrdude/avrupd.o"
	@echo "... libs/avrdude/avrupd.i"
	@echo "... libs/avrdude/avrupd.s"
	@echo "... libs/avrdude/fileio.o"
	@echo "... libs/avrdude/fileio.i"
	@echo "... libs/avrdude/fileio.s"
	@echo "... libs/avrdude/pgm.o"
	@echo "... libs/avrdude/pgm.i"
	@echo "... libs/avrdude/pgm.s"
	@echo "... libs/avrdude/safemode.o"
	@echo "... libs/avrdude/safemode.i"
	@echo "... libs/avrdude/safemode.s"
	@echo "... libs/hardware/433gpio.o"
	@echo "... libs/hardware/433gpio.i"
	@echo "... libs/hardware/433gpio.s"
	@echo "... libs/hardware/433lirc.o"
	@echo "... libs/hardware/433lirc.i"
	@echo "... libs/hardware/433lirc.s"
	@echo "... libs/hardware/433pilight.o"
	@echo "... libs/hardware/433pilight.i"
	@echo "... libs/hardware/433pilight.s"
	@echo "... libs/hardware/none.o"
	@echo "... libs/hardware/none.i"
	@echo "... libs/hardware/none.s"
	@echo "... libs/pilight/binary.o"
	@echo "... libs/pilight/binary.i"
	@echo "... libs/pilight/binary.s"
	@echo "... libs/pilight/common.o"
	@echo "... libs/pilight/common.i"
	@echo "... libs/pilight/common.s"
	@echo "... libs/pilight/config.o"
	@echo "... libs/pilight/config.i"
	@echo "... libs/pilight/config.s"
	@echo "... libs/pilight/datetime.o"
	@echo "... libs/pilight/datetime.i"
	@echo "... libs/pilight/datetime.s"
	@echo "... libs/pilight/dso.o"
	@echo "... libs/pilight/dso.i"
	@echo "... libs/pilight/dso.s"
	@echo "... libs/pilight/fcache.o"
	@echo "... libs/pilight/fcache.i"
	@echo "... libs/pilight/fcache.s"
	@echo "... libs/pilight/firmware.o"
	@echo "... libs/pilight/firmware.i"
	@echo "... libs/pilight/firmware.s"
	@echo "... libs/pilight/gc.o"
	@echo "... libs/pilight/gc.i"
	@echo "... libs/pilight/gc.s"
	@echo "... libs/pilight/hardware.o"
	@echo "... libs/pilight/hardware.i"
	@echo "... libs/pilight/hardware.s"
	@echo "... libs/pilight/http_lib.o"
	@echo "... libs/pilight/http_lib.i"
	@echo "... libs/pilight/http_lib.s"
	@echo "... libs/pilight/irq.o"
	@echo "... libs/pilight/irq.i"
	@echo "... libs/pilight/irq.s"
	@echo "... libs/pilight/json.o"
	@echo "... libs/pilight/json.i"
	@echo "... libs/pilight/json.s"
	@echo "... libs/pilight/log.o"
	@echo "... libs/pilight/log.i"
	@echo "... libs/pilight/log.s"
	@echo "... libs/pilight/mongoose.o"
	@echo "... libs/pilight/mongoose.i"
	@echo "... libs/pilight/mongoose.s"
	@echo "... libs/pilight/options.o"
	@echo "... libs/pilight/options.i"
	@echo "... libs/pilight/options.s"
	@echo "... libs/pilight/proc.o"
	@echo "... libs/pilight/proc.i"
	@echo "... libs/pilight/proc.s"
	@echo "... libs/pilight/protocol.o"
	@echo "... libs/pilight/protocol.i"
	@echo "... libs/pilight/protocol.s"
	@echo "... libs/pilight/settings.o"
	@echo "... libs/pilight/settings.i"
	@echo "... libs/pilight/settings.s"
	@echo "... libs/pilight/socket.o"
	@echo "... libs/pilight/socket.i"
	@echo "... libs/pilight/socket.s"
	@echo "... libs/pilight/ssdp.o"
	@echo "... libs/pilight/ssdp.i"
	@echo "... libs/pilight/ssdp.s"
	@echo "... libs/pilight/threads.o"
	@echo "... libs/pilight/threads.i"
	@echo "... libs/pilight/threads.s"
	@echo "... libs/pilight/update.o"
	@echo "... libs/pilight/update.i"
	@echo "... libs/pilight/update.s"
	@echo "... libs/pilight/webserver.o"
	@echo "... libs/pilight/webserver.i"
	@echo "... libs/pilight/webserver.s"
	@echo "... libs/pilight/wiringPi.o"
	@echo "... libs/pilight/wiringPi.i"
	@echo "... libs/pilight/wiringPi.s"
	@echo "... libs/pilight/wiringPiI2C.o"
	@echo "... libs/pilight/wiringPiI2C.i"
	@echo "... libs/pilight/wiringPiI2C.s"
	@echo "... libs/protocols/arctech_switch_old.o"
	@echo "... libs/protocols/arctech_switch_old.i"
	@echo "... libs/protocols/arctech_switch_old.s"
	@echo "... libs/protocols/datetime.o"
	@echo "... libs/protocols/datetime.i"
	@echo "... libs/protocols/datetime.s"
	@echo "... libs/protocols/generic_switch.o"
	@echo "... libs/protocols/generic_switch.i"
	@echo "... libs/protocols/generic_switch.s"
	@echo "... libs/protocols/lirc.o"
	@echo "... libs/protocols/lirc.i"
	@echo "... libs/protocols/lirc.s"
	@echo "... libs/protocols/pilight_firmware_v2.o"
	@echo "... libs/protocols/pilight_firmware_v2.i"
	@echo "... libs/protocols/pilight_firmware_v2.s"
	@echo "... libs/protocols/pilight_firmware_v3.o"
	@echo "... libs/protocols/pilight_firmware_v3.i"
	@echo "... libs/protocols/pilight_firmware_v3.s"
	@echo "... libs/protocols/quigg_gt1000.o"
	@echo "... libs/protocols/quigg_gt1000.i"
	@echo "... libs/protocols/quigg_gt1000.s"
	@echo "... libs/protocols/quigg_switch.o"
	@echo "... libs/protocols/quigg_switch.i"
	@echo "... libs/protocols/quigg_switch.s"
	@echo "... libs/protocols/raw.o"
	@echo "... libs/protocols/raw.i"
	@echo "... libs/protocols/raw.s"
	@echo "... libs/protocols/relay.o"
	@echo "... libs/protocols/relay.i"
	@echo "... libs/protocols/relay.s"
	@echo "... libs/protocols/xbmc.o"
	@echo "... libs/protocols/xbmc.i"
	@echo "... libs/protocols/xbmc.s"
	@echo "... raw.o"
	@echo "... raw.i"
	@echo "... raw.s"
	@echo "... receive.o"
	@echo "... receive.i"
	@echo "... receive.s"
	@echo "... send.o"
	@echo "... send.i"
	@echo "... send.s"
	@echo "... uuid.o"
	@echo "... uuid.i"
	@echo "... uuid.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

