# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/rpi/433.92/daemon1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/rpi/433.92/daemon1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/rpi/433.92/daemon1/CMakeFiles /media/rpi/433.92/daemon1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/rpi/433.92/daemon1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pilight

# Build rule for target.
pilight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight
.PHONY : pilight

# fast build rule for target.
pilight/fast:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/build
.PHONY : pilight/fast

#=============================================================================
# Target rules for targets named pilight-control

# Build rule for target.
pilight-control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-control
.PHONY : pilight-control

# fast build rule for target.
pilight-control/fast:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/build
.PHONY : pilight-control/fast

#=============================================================================
# Target rules for targets named pilight-daemon

# Build rule for target.
pilight-daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-daemon
.PHONY : pilight-daemon

# fast build rule for target.
pilight-daemon/fast:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/build
.PHONY : pilight-daemon/fast

#=============================================================================
# Target rules for targets named pilight-debug

# Build rule for target.
pilight-debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-debug
.PHONY : pilight-debug

# fast build rule for target.
pilight-debug/fast:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/build
.PHONY : pilight-debug/fast

#=============================================================================
# Target rules for targets named pilight-learn

# Build rule for target.
pilight-learn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-learn
.PHONY : pilight-learn

# fast build rule for target.
pilight-learn/fast:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/build
.PHONY : pilight-learn/fast

#=============================================================================
# Target rules for targets named pilight-raw

# Build rule for target.
pilight-raw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-raw
.PHONY : pilight-raw

# fast build rule for target.
pilight-raw/fast:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/build
.PHONY : pilight-raw/fast

#=============================================================================
# Target rules for targets named pilight-receive

# Build rule for target.
pilight-receive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-receive
.PHONY : pilight-receive

# fast build rule for target.
pilight-receive/fast:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/build
.PHONY : pilight-receive/fast

#=============================================================================
# Target rules for targets named pilight-send

# Build rule for target.
pilight-send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight-send
.PHONY : pilight-send

# fast build rule for target.
pilight-send/fast:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/build
.PHONY : pilight-send/fast

#=============================================================================
# Target rules for targets named pilight_shared

# Build rule for target.
pilight_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight_shared
.PHONY : pilight_shared

# fast build rule for target.
pilight_shared/fast:
	$(MAKE) -f CMakeFiles/pilight_shared.dir/build.make CMakeFiles/pilight_shared.dir/build
.PHONY : pilight_shared/fast

#=============================================================================
# Target rules for targets named pilight_static

# Build rule for target.
pilight_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pilight_static
.PHONY : pilight_static

# fast build rule for target.
pilight_static/fast:
	$(MAKE) -f CMakeFiles/pilight_static.dir/build.make CMakeFiles/pilight_static.dir/build
.PHONY : pilight_static/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

control.o: control.c.o
.PHONY : control.o

# target to build an object file
control.c.o:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/control.c.o
.PHONY : control.c.o

control.i: control.c.i
.PHONY : control.i

# target to preprocess a source file
control.c.i:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/control.c.i
.PHONY : control.c.i

control.s: control.c.s
.PHONY : control.s

# target to generate assembly for a file
control.c.s:
	$(MAKE) -f CMakeFiles/pilight-control.dir/build.make CMakeFiles/pilight-control.dir/control.c.s
.PHONY : control.c.s

daemon.o: daemon.c.o
.PHONY : daemon.o

# target to build an object file
daemon.c.o:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/daemon.c.o
.PHONY : daemon.c.o

daemon.i: daemon.c.i
.PHONY : daemon.i

# target to preprocess a source file
daemon.c.i:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/daemon.c.i
.PHONY : daemon.c.i

daemon.s: daemon.c.s
.PHONY : daemon.s

# target to generate assembly for a file
daemon.c.s:
	$(MAKE) -f CMakeFiles/pilight-daemon.dir/build.make CMakeFiles/pilight-daemon.dir/daemon.c.s
.PHONY : daemon.c.s

debug.o: debug.c.o
.PHONY : debug.o

# target to build an object file
debug.c.o:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/debug.c.o
.PHONY : debug.c.o

debug.i: debug.c.i
.PHONY : debug.i

# target to preprocess a source file
debug.c.i:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/debug.c.i
.PHONY : debug.c.i

debug.s: debug.c.s
.PHONY : debug.s

# target to generate assembly for a file
debug.c.s:
	$(MAKE) -f CMakeFiles/pilight-debug.dir/build.make CMakeFiles/pilight-debug.dir/debug.c.s
.PHONY : debug.c.s

learn.o: learn.c.o
.PHONY : learn.o

# target to build an object file
learn.c.o:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/learn.c.o
.PHONY : learn.c.o

learn.i: learn.c.i
.PHONY : learn.i

# target to preprocess a source file
learn.c.i:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/learn.c.i
.PHONY : learn.c.i

learn.s: learn.c.s
.PHONY : learn.s

# target to generate assembly for a file
learn.c.s:
	$(MAKE) -f CMakeFiles/pilight-learn.dir/build.make CMakeFiles/pilight-learn.dir/learn.c.s
.PHONY : learn.c.s

libs/hardwares/gpio.o: libs/hardwares/gpio.c.o
.PHONY : libs/hardwares/gpio.o

# target to build an object file
libs/hardwares/gpio.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/gpio.c.o
.PHONY : libs/hardwares/gpio.c.o

libs/hardwares/gpio.i: libs/hardwares/gpio.c.i
.PHONY : libs/hardwares/gpio.i

# target to preprocess a source file
libs/hardwares/gpio.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/gpio.c.i
.PHONY : libs/hardwares/gpio.c.i

libs/hardwares/gpio.s: libs/hardwares/gpio.c.s
.PHONY : libs/hardwares/gpio.s

# target to generate assembly for a file
libs/hardwares/gpio.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/gpio.c.s
.PHONY : libs/hardwares/gpio.c.s

libs/hardwares/module.o: libs/hardwares/module.c.o
.PHONY : libs/hardwares/module.o

# target to build an object file
libs/hardwares/module.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/module.c.o
.PHONY : libs/hardwares/module.c.o

libs/hardwares/module.i: libs/hardwares/module.c.i
.PHONY : libs/hardwares/module.i

# target to preprocess a source file
libs/hardwares/module.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/module.c.i
.PHONY : libs/hardwares/module.c.i

libs/hardwares/module.s: libs/hardwares/module.c.s
.PHONY : libs/hardwares/module.s

# target to generate assembly for a file
libs/hardwares/module.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/module.c.s
.PHONY : libs/hardwares/module.c.s

libs/hardwares/none.o: libs/hardwares/none.c.o
.PHONY : libs/hardwares/none.o

# target to build an object file
libs/hardwares/none.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/none.c.o
.PHONY : libs/hardwares/none.c.o

libs/hardwares/none.i: libs/hardwares/none.c.i
.PHONY : libs/hardwares/none.i

# target to preprocess a source file
libs/hardwares/none.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/none.c.i
.PHONY : libs/hardwares/none.c.i

libs/hardwares/none.s: libs/hardwares/none.c.s
.PHONY : libs/hardwares/none.s

# target to generate assembly for a file
libs/hardwares/none.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/hardwares/none.c.s
.PHONY : libs/hardwares/none.c.s

libs/pilight/binary.o: libs/pilight/binary.c.o
.PHONY : libs/pilight/binary.o

# target to build an object file
libs/pilight/binary.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/binary.c.o
.PHONY : libs/pilight/binary.c.o

libs/pilight/binary.i: libs/pilight/binary.c.i
.PHONY : libs/pilight/binary.i

# target to preprocess a source file
libs/pilight/binary.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/binary.c.i
.PHONY : libs/pilight/binary.c.i

libs/pilight/binary.s: libs/pilight/binary.c.s
.PHONY : libs/pilight/binary.s

# target to generate assembly for a file
libs/pilight/binary.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/binary.c.s
.PHONY : libs/pilight/binary.c.s

libs/pilight/config.o: libs/pilight/config.c.o
.PHONY : libs/pilight/config.o

# target to build an object file
libs/pilight/config.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/config.c.o
.PHONY : libs/pilight/config.c.o

libs/pilight/config.i: libs/pilight/config.c.i
.PHONY : libs/pilight/config.i

# target to preprocess a source file
libs/pilight/config.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/config.c.i
.PHONY : libs/pilight/config.c.i

libs/pilight/config.s: libs/pilight/config.c.s
.PHONY : libs/pilight/config.s

# target to generate assembly for a file
libs/pilight/config.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/config.c.s
.PHONY : libs/pilight/config.c.s

libs/pilight/fcache.o: libs/pilight/fcache.c.o
.PHONY : libs/pilight/fcache.o

# target to build an object file
libs/pilight/fcache.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/fcache.c.o
.PHONY : libs/pilight/fcache.c.o

libs/pilight/fcache.i: libs/pilight/fcache.c.i
.PHONY : libs/pilight/fcache.i

# target to preprocess a source file
libs/pilight/fcache.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/fcache.c.i
.PHONY : libs/pilight/fcache.c.i

libs/pilight/fcache.s: libs/pilight/fcache.c.s
.PHONY : libs/pilight/fcache.s

# target to generate assembly for a file
libs/pilight/fcache.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/fcache.c.s
.PHONY : libs/pilight/fcache.c.s

libs/pilight/gc.o: libs/pilight/gc.c.o
.PHONY : libs/pilight/gc.o

# target to build an object file
libs/pilight/gc.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/gc.c.o
.PHONY : libs/pilight/gc.c.o

libs/pilight/gc.i: libs/pilight/gc.c.i
.PHONY : libs/pilight/gc.i

# target to preprocess a source file
libs/pilight/gc.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/gc.c.i
.PHONY : libs/pilight/gc.c.i

libs/pilight/gc.s: libs/pilight/gc.c.s
.PHONY : libs/pilight/gc.s

# target to generate assembly for a file
libs/pilight/gc.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/gc.c.s
.PHONY : libs/pilight/gc.c.s

libs/pilight/hardware.o: libs/pilight/hardware.c.o
.PHONY : libs/pilight/hardware.o

# target to build an object file
libs/pilight/hardware.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/hardware.c.o
.PHONY : libs/pilight/hardware.c.o

libs/pilight/hardware.i: libs/pilight/hardware.c.i
.PHONY : libs/pilight/hardware.i

# target to preprocess a source file
libs/pilight/hardware.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/hardware.c.i
.PHONY : libs/pilight/hardware.c.i

libs/pilight/hardware.s: libs/pilight/hardware.c.s
.PHONY : libs/pilight/hardware.s

# target to generate assembly for a file
libs/pilight/hardware.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/hardware.c.s
.PHONY : libs/pilight/hardware.c.s

libs/pilight/irq.o: libs/pilight/irq.c.o
.PHONY : libs/pilight/irq.o

# target to build an object file
libs/pilight/irq.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/irq.c.o
.PHONY : libs/pilight/irq.c.o

libs/pilight/irq.i: libs/pilight/irq.c.i
.PHONY : libs/pilight/irq.i

# target to preprocess a source file
libs/pilight/irq.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/irq.c.i
.PHONY : libs/pilight/irq.c.i

libs/pilight/irq.s: libs/pilight/irq.c.s
.PHONY : libs/pilight/irq.s

# target to generate assembly for a file
libs/pilight/irq.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/irq.c.s
.PHONY : libs/pilight/irq.c.s

libs/pilight/json.o: libs/pilight/json.c.o
.PHONY : libs/pilight/json.o

# target to build an object file
libs/pilight/json.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/json.c.o
.PHONY : libs/pilight/json.c.o

libs/pilight/json.i: libs/pilight/json.c.i
.PHONY : libs/pilight/json.i

# target to preprocess a source file
libs/pilight/json.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/json.c.i
.PHONY : libs/pilight/json.c.i

libs/pilight/json.s: libs/pilight/json.c.s
.PHONY : libs/pilight/json.s

# target to generate assembly for a file
libs/pilight/json.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/json.c.s
.PHONY : libs/pilight/json.c.s

libs/pilight/log.o: libs/pilight/log.c.o
.PHONY : libs/pilight/log.o

# target to build an object file
libs/pilight/log.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/log.c.o
.PHONY : libs/pilight/log.c.o

libs/pilight/log.i: libs/pilight/log.c.i
.PHONY : libs/pilight/log.i

# target to preprocess a source file
libs/pilight/log.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/log.c.i
.PHONY : libs/pilight/log.c.i

libs/pilight/log.s: libs/pilight/log.c.s
.PHONY : libs/pilight/log.s

# target to generate assembly for a file
libs/pilight/log.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/log.c.s
.PHONY : libs/pilight/log.c.s

libs/pilight/options.o: libs/pilight/options.c.o
.PHONY : libs/pilight/options.o

# target to build an object file
libs/pilight/options.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/options.c.o
.PHONY : libs/pilight/options.c.o

libs/pilight/options.i: libs/pilight/options.c.i
.PHONY : libs/pilight/options.i

# target to preprocess a source file
libs/pilight/options.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/options.c.i
.PHONY : libs/pilight/options.c.i

libs/pilight/options.s: libs/pilight/options.c.s
.PHONY : libs/pilight/options.s

# target to generate assembly for a file
libs/pilight/options.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/options.c.s
.PHONY : libs/pilight/options.c.s

libs/pilight/protocol.o: libs/pilight/protocol.c.o
.PHONY : libs/pilight/protocol.o

# target to build an object file
libs/pilight/protocol.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/protocol.c.o
.PHONY : libs/pilight/protocol.c.o

libs/pilight/protocol.i: libs/pilight/protocol.c.i
.PHONY : libs/pilight/protocol.i

# target to preprocess a source file
libs/pilight/protocol.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/protocol.c.i
.PHONY : libs/pilight/protocol.c.i

libs/pilight/protocol.s: libs/pilight/protocol.c.s
.PHONY : libs/pilight/protocol.s

# target to generate assembly for a file
libs/pilight/protocol.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/protocol.c.s
.PHONY : libs/pilight/protocol.c.s

libs/pilight/settings.o: libs/pilight/settings.c.o
.PHONY : libs/pilight/settings.o

# target to build an object file
libs/pilight/settings.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/settings.c.o
.PHONY : libs/pilight/settings.c.o

libs/pilight/settings.i: libs/pilight/settings.c.i
.PHONY : libs/pilight/settings.i

# target to preprocess a source file
libs/pilight/settings.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/settings.c.i
.PHONY : libs/pilight/settings.c.i

libs/pilight/settings.s: libs/pilight/settings.c.s
.PHONY : libs/pilight/settings.s

# target to generate assembly for a file
libs/pilight/settings.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/settings.c.s
.PHONY : libs/pilight/settings.c.s

libs/pilight/socket.o: libs/pilight/socket.c.o
.PHONY : libs/pilight/socket.o

# target to build an object file
libs/pilight/socket.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/socket.c.o
.PHONY : libs/pilight/socket.c.o

libs/pilight/socket.i: libs/pilight/socket.c.i
.PHONY : libs/pilight/socket.i

# target to preprocess a source file
libs/pilight/socket.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/socket.c.i
.PHONY : libs/pilight/socket.c.i

libs/pilight/socket.s: libs/pilight/socket.c.s
.PHONY : libs/pilight/socket.s

# target to generate assembly for a file
libs/pilight/socket.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/socket.c.s
.PHONY : libs/pilight/socket.c.s

libs/pilight/threads.o: libs/pilight/threads.c.o
.PHONY : libs/pilight/threads.o

# target to build an object file
libs/pilight/threads.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/threads.c.o
.PHONY : libs/pilight/threads.c.o

libs/pilight/threads.i: libs/pilight/threads.c.i
.PHONY : libs/pilight/threads.i

# target to preprocess a source file
libs/pilight/threads.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/threads.c.i
.PHONY : libs/pilight/threads.c.i

libs/pilight/threads.s: libs/pilight/threads.c.s
.PHONY : libs/pilight/threads.s

# target to generate assembly for a file
libs/pilight/threads.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/threads.c.s
.PHONY : libs/pilight/threads.c.s

libs/pilight/webserver.o: libs/pilight/webserver.c.o
.PHONY : libs/pilight/webserver.o

# target to build an object file
libs/pilight/webserver.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/webserver.c.o
.PHONY : libs/pilight/webserver.c.o

libs/pilight/webserver.i: libs/pilight/webserver.c.i
.PHONY : libs/pilight/webserver.i

# target to preprocess a source file
libs/pilight/webserver.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/webserver.c.i
.PHONY : libs/pilight/webserver.c.i

libs/pilight/webserver.s: libs/pilight/webserver.c.s
.PHONY : libs/pilight/webserver.s

# target to generate assembly for a file
libs/pilight/webserver.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/webserver.c.s
.PHONY : libs/pilight/webserver.c.s

libs/pilight/wiringPi.o: libs/pilight/wiringPi.c.o
.PHONY : libs/pilight/wiringPi.o

# target to build an object file
libs/pilight/wiringPi.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPi.c.o
.PHONY : libs/pilight/wiringPi.c.o

libs/pilight/wiringPi.i: libs/pilight/wiringPi.c.i
.PHONY : libs/pilight/wiringPi.i

# target to preprocess a source file
libs/pilight/wiringPi.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPi.c.i
.PHONY : libs/pilight/wiringPi.c.i

libs/pilight/wiringPi.s: libs/pilight/wiringPi.c.s
.PHONY : libs/pilight/wiringPi.s

# target to generate assembly for a file
libs/pilight/wiringPi.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/pilight/wiringPi.c.s
.PHONY : libs/pilight/wiringPi.c.s

libs/protocols/alecto.o: libs/protocols/alecto.c.o
.PHONY : libs/protocols/alecto.o

# target to build an object file
libs/protocols/alecto.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/alecto.c.o
.PHONY : libs/protocols/alecto.c.o

libs/protocols/alecto.i: libs/protocols/alecto.c.i
.PHONY : libs/protocols/alecto.i

# target to preprocess a source file
libs/protocols/alecto.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/alecto.c.i
.PHONY : libs/protocols/alecto.c.i

libs/protocols/alecto.s: libs/protocols/alecto.c.s
.PHONY : libs/protocols/alecto.s

# target to generate assembly for a file
libs/protocols/alecto.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/alecto.c.s
.PHONY : libs/protocols/alecto.c.s

libs/protocols/arctech_dimmer.o: libs/protocols/arctech_dimmer.c.o
.PHONY : libs/protocols/arctech_dimmer.o

# target to build an object file
libs/protocols/arctech_dimmer.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_dimmer.c.o
.PHONY : libs/protocols/arctech_dimmer.c.o

libs/protocols/arctech_dimmer.i: libs/protocols/arctech_dimmer.c.i
.PHONY : libs/protocols/arctech_dimmer.i

# target to preprocess a source file
libs/protocols/arctech_dimmer.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_dimmer.c.i
.PHONY : libs/protocols/arctech_dimmer.c.i

libs/protocols/arctech_dimmer.s: libs/protocols/arctech_dimmer.c.s
.PHONY : libs/protocols/arctech_dimmer.s

# target to generate assembly for a file
libs/protocols/arctech_dimmer.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_dimmer.c.s
.PHONY : libs/protocols/arctech_dimmer.c.s

libs/protocols/arctech_old.o: libs/protocols/arctech_old.c.o
.PHONY : libs/protocols/arctech_old.o

# target to build an object file
libs/protocols/arctech_old.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_old.c.o
.PHONY : libs/protocols/arctech_old.c.o

libs/protocols/arctech_old.i: libs/protocols/arctech_old.c.i
.PHONY : libs/protocols/arctech_old.i

# target to preprocess a source file
libs/protocols/arctech_old.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_old.c.i
.PHONY : libs/protocols/arctech_old.c.i

libs/protocols/arctech_old.s: libs/protocols/arctech_old.c.s
.PHONY : libs/protocols/arctech_old.s

# target to generate assembly for a file
libs/protocols/arctech_old.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_old.c.s
.PHONY : libs/protocols/arctech_old.c.s

libs/protocols/arctech_switch.o: libs/protocols/arctech_switch.c.o
.PHONY : libs/protocols/arctech_switch.o

# target to build an object file
libs/protocols/arctech_switch.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_switch.c.o
.PHONY : libs/protocols/arctech_switch.c.o

libs/protocols/arctech_switch.i: libs/protocols/arctech_switch.c.i
.PHONY : libs/protocols/arctech_switch.i

# target to preprocess a source file
libs/protocols/arctech_switch.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_switch.c.i
.PHONY : libs/protocols/arctech_switch.c.i

libs/protocols/arctech_switch.s: libs/protocols/arctech_switch.c.s
.PHONY : libs/protocols/arctech_switch.s

# target to generate assembly for a file
libs/protocols/arctech_switch.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/arctech_switch.c.s
.PHONY : libs/protocols/arctech_switch.c.s

libs/protocols/ds18b20.o: libs/protocols/ds18b20.c.o
.PHONY : libs/protocols/ds18b20.o

# target to build an object file
libs/protocols/ds18b20.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/ds18b20.c.o
.PHONY : libs/protocols/ds18b20.c.o

libs/protocols/ds18b20.i: libs/protocols/ds18b20.c.i
.PHONY : libs/protocols/ds18b20.i

# target to preprocess a source file
libs/protocols/ds18b20.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/ds18b20.c.i
.PHONY : libs/protocols/ds18b20.c.i

libs/protocols/ds18b20.s: libs/protocols/ds18b20.c.s
.PHONY : libs/protocols/ds18b20.s

# target to generate assembly for a file
libs/protocols/ds18b20.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/ds18b20.c.s
.PHONY : libs/protocols/ds18b20.c.s

libs/protocols/generic_dimmer.o: libs/protocols/generic_dimmer.c.o
.PHONY : libs/protocols/generic_dimmer.o

# target to build an object file
libs/protocols/generic_dimmer.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_dimmer.c.o
.PHONY : libs/protocols/generic_dimmer.c.o

libs/protocols/generic_dimmer.i: libs/protocols/generic_dimmer.c.i
.PHONY : libs/protocols/generic_dimmer.i

# target to preprocess a source file
libs/protocols/generic_dimmer.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_dimmer.c.i
.PHONY : libs/protocols/generic_dimmer.c.i

libs/protocols/generic_dimmer.s: libs/protocols/generic_dimmer.c.s
.PHONY : libs/protocols/generic_dimmer.s

# target to generate assembly for a file
libs/protocols/generic_dimmer.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_dimmer.c.s
.PHONY : libs/protocols/generic_dimmer.c.s

libs/protocols/generic_switch.o: libs/protocols/generic_switch.c.o
.PHONY : libs/protocols/generic_switch.o

# target to build an object file
libs/protocols/generic_switch.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_switch.c.o
.PHONY : libs/protocols/generic_switch.c.o

libs/protocols/generic_switch.i: libs/protocols/generic_switch.c.i
.PHONY : libs/protocols/generic_switch.i

# target to preprocess a source file
libs/protocols/generic_switch.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_switch.c.i
.PHONY : libs/protocols/generic_switch.c.i

libs/protocols/generic_switch.s: libs/protocols/generic_switch.c.s
.PHONY : libs/protocols/generic_switch.s

# target to generate assembly for a file
libs/protocols/generic_switch.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_switch.c.s
.PHONY : libs/protocols/generic_switch.c.s

libs/protocols/generic_weather.o: libs/protocols/generic_weather.c.o
.PHONY : libs/protocols/generic_weather.o

# target to build an object file
libs/protocols/generic_weather.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_weather.c.o
.PHONY : libs/protocols/generic_weather.c.o

libs/protocols/generic_weather.i: libs/protocols/generic_weather.c.i
.PHONY : libs/protocols/generic_weather.i

# target to preprocess a source file
libs/protocols/generic_weather.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_weather.c.i
.PHONY : libs/protocols/generic_weather.c.i

libs/protocols/generic_weather.s: libs/protocols/generic_weather.c.s
.PHONY : libs/protocols/generic_weather.s

# target to generate assembly for a file
libs/protocols/generic_weather.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/generic_weather.c.s
.PHONY : libs/protocols/generic_weather.c.s

libs/protocols/home_easy_old.o: libs/protocols/home_easy_old.c.o
.PHONY : libs/protocols/home_easy_old.o

# target to build an object file
libs/protocols/home_easy_old.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/home_easy_old.c.o
.PHONY : libs/protocols/home_easy_old.c.o

libs/protocols/home_easy_old.i: libs/protocols/home_easy_old.c.i
.PHONY : libs/protocols/home_easy_old.i

# target to preprocess a source file
libs/protocols/home_easy_old.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/home_easy_old.c.i
.PHONY : libs/protocols/home_easy_old.c.i

libs/protocols/home_easy_old.s: libs/protocols/home_easy_old.c.s
.PHONY : libs/protocols/home_easy_old.s

# target to generate assembly for a file
libs/protocols/home_easy_old.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/home_easy_old.c.s
.PHONY : libs/protocols/home_easy_old.c.s

libs/protocols/impuls.o: libs/protocols/impuls.c.o
.PHONY : libs/protocols/impuls.o

# target to build an object file
libs/protocols/impuls.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/impuls.c.o
.PHONY : libs/protocols/impuls.c.o

libs/protocols/impuls.i: libs/protocols/impuls.c.i
.PHONY : libs/protocols/impuls.i

# target to preprocess a source file
libs/protocols/impuls.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/impuls.c.i
.PHONY : libs/protocols/impuls.c.i

libs/protocols/impuls.s: libs/protocols/impuls.c.s
.PHONY : libs/protocols/impuls.s

# target to generate assembly for a file
libs/protocols/impuls.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/impuls.c.s
.PHONY : libs/protocols/impuls.c.s

libs/protocols/raw.o: libs/protocols/raw.c.o
.PHONY : libs/protocols/raw.o

# target to build an object file
libs/protocols/raw.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/raw.c.o
.PHONY : libs/protocols/raw.c.o

libs/protocols/raw.i: libs/protocols/raw.c.i
.PHONY : libs/protocols/raw.i

# target to preprocess a source file
libs/protocols/raw.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/raw.c.i
.PHONY : libs/protocols/raw.c.i

libs/protocols/raw.s: libs/protocols/raw.c.s
.PHONY : libs/protocols/raw.s

# target to generate assembly for a file
libs/protocols/raw.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/raw.c.s
.PHONY : libs/protocols/raw.c.s

libs/protocols/relay.o: libs/protocols/relay.c.o
.PHONY : libs/protocols/relay.o

# target to build an object file
libs/protocols/relay.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/relay.c.o
.PHONY : libs/protocols/relay.c.o

libs/protocols/relay.i: libs/protocols/relay.c.i
.PHONY : libs/protocols/relay.i

# target to preprocess a source file
libs/protocols/relay.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/relay.c.i
.PHONY : libs/protocols/relay.c.i

libs/protocols/relay.s: libs/protocols/relay.c.s
.PHONY : libs/protocols/relay.s

# target to generate assembly for a file
libs/protocols/relay.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/relay.c.s
.PHONY : libs/protocols/relay.c.s

libs/protocols/sartano.o: libs/protocols/sartano.c.o
.PHONY : libs/protocols/sartano.o

# target to build an object file
libs/protocols/sartano.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/sartano.c.o
.PHONY : libs/protocols/sartano.c.o

libs/protocols/sartano.i: libs/protocols/sartano.c.i
.PHONY : libs/protocols/sartano.i

# target to preprocess a source file
libs/protocols/sartano.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/sartano.c.i
.PHONY : libs/protocols/sartano.c.i

libs/protocols/sartano.s: libs/protocols/sartano.c.s
.PHONY : libs/protocols/sartano.s

# target to generate assembly for a file
libs/protocols/sartano.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/protocols/sartano.c.s
.PHONY : libs/protocols/sartano.c.s

libs/websockets/base64-decode.o: libs/websockets/base64-decode.c.o
.PHONY : libs/websockets/base64-decode.o

# target to build an object file
libs/websockets/base64-decode.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/base64-decode.c.o
.PHONY : libs/websockets/base64-decode.c.o

libs/websockets/base64-decode.i: libs/websockets/base64-decode.c.i
.PHONY : libs/websockets/base64-decode.i

# target to preprocess a source file
libs/websockets/base64-decode.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/base64-decode.c.i
.PHONY : libs/websockets/base64-decode.c.i

libs/websockets/base64-decode.s: libs/websockets/base64-decode.c.s
.PHONY : libs/websockets/base64-decode.s

# target to generate assembly for a file
libs/websockets/base64-decode.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/base64-decode.c.s
.PHONY : libs/websockets/base64-decode.c.s

libs/websockets/daemonize.o: libs/websockets/daemonize.c.o
.PHONY : libs/websockets/daemonize.o

# target to build an object file
libs/websockets/daemonize.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/daemonize.c.o
.PHONY : libs/websockets/daemonize.c.o

libs/websockets/daemonize.i: libs/websockets/daemonize.c.i
.PHONY : libs/websockets/daemonize.i

# target to preprocess a source file
libs/websockets/daemonize.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/daemonize.c.i
.PHONY : libs/websockets/daemonize.c.i

libs/websockets/daemonize.s: libs/websockets/daemonize.c.s
.PHONY : libs/websockets/daemonize.s

# target to generate assembly for a file
libs/websockets/daemonize.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/daemonize.c.s
.PHONY : libs/websockets/daemonize.c.s

libs/websockets/getifaddrs.o: libs/websockets/getifaddrs.c.o
.PHONY : libs/websockets/getifaddrs.o

# target to build an object file
libs/websockets/getifaddrs.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/getifaddrs.c.o
.PHONY : libs/websockets/getifaddrs.c.o

libs/websockets/getifaddrs.i: libs/websockets/getifaddrs.c.i
.PHONY : libs/websockets/getifaddrs.i

# target to preprocess a source file
libs/websockets/getifaddrs.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/getifaddrs.c.i
.PHONY : libs/websockets/getifaddrs.c.i

libs/websockets/getifaddrs.s: libs/websockets/getifaddrs.c.s
.PHONY : libs/websockets/getifaddrs.s

# target to generate assembly for a file
libs/websockets/getifaddrs.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/getifaddrs.c.s
.PHONY : libs/websockets/getifaddrs.c.s

libs/websockets/handshake.o: libs/websockets/handshake.c.o
.PHONY : libs/websockets/handshake.o

# target to build an object file
libs/websockets/handshake.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/handshake.c.o
.PHONY : libs/websockets/handshake.c.o

libs/websockets/handshake.i: libs/websockets/handshake.c.i
.PHONY : libs/websockets/handshake.i

# target to preprocess a source file
libs/websockets/handshake.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/handshake.c.i
.PHONY : libs/websockets/handshake.c.i

libs/websockets/handshake.s: libs/websockets/handshake.c.s
.PHONY : libs/websockets/handshake.s

# target to generate assembly for a file
libs/websockets/handshake.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/handshake.c.s
.PHONY : libs/websockets/handshake.c.s

libs/websockets/libwebsockets.o: libs/websockets/libwebsockets.c.o
.PHONY : libs/websockets/libwebsockets.o

# target to build an object file
libs/websockets/libwebsockets.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/libwebsockets.c.o
.PHONY : libs/websockets/libwebsockets.c.o

libs/websockets/libwebsockets.i: libs/websockets/libwebsockets.c.i
.PHONY : libs/websockets/libwebsockets.i

# target to preprocess a source file
libs/websockets/libwebsockets.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/libwebsockets.c.i
.PHONY : libs/websockets/libwebsockets.c.i

libs/websockets/libwebsockets.s: libs/websockets/libwebsockets.c.s
.PHONY : libs/websockets/libwebsockets.s

# target to generate assembly for a file
libs/websockets/libwebsockets.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/libwebsockets.c.s
.PHONY : libs/websockets/libwebsockets.c.s

libs/websockets/output.o: libs/websockets/output.c.o
.PHONY : libs/websockets/output.o

# target to build an object file
libs/websockets/output.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/output.c.o
.PHONY : libs/websockets/output.c.o

libs/websockets/output.i: libs/websockets/output.c.i
.PHONY : libs/websockets/output.i

# target to preprocess a source file
libs/websockets/output.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/output.c.i
.PHONY : libs/websockets/output.c.i

libs/websockets/output.s: libs/websockets/output.c.s
.PHONY : libs/websockets/output.s

# target to generate assembly for a file
libs/websockets/output.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/output.c.s
.PHONY : libs/websockets/output.c.s

libs/websockets/parsers.o: libs/websockets/parsers.c.o
.PHONY : libs/websockets/parsers.o

# target to build an object file
libs/websockets/parsers.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/parsers.c.o
.PHONY : libs/websockets/parsers.c.o

libs/websockets/parsers.i: libs/websockets/parsers.c.i
.PHONY : libs/websockets/parsers.i

# target to preprocess a source file
libs/websockets/parsers.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/parsers.c.i
.PHONY : libs/websockets/parsers.c.i

libs/websockets/parsers.s: libs/websockets/parsers.c.s
.PHONY : libs/websockets/parsers.s

# target to generate assembly for a file
libs/websockets/parsers.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/parsers.c.s
.PHONY : libs/websockets/parsers.c.s

libs/websockets/server-handshake.o: libs/websockets/server-handshake.c.o
.PHONY : libs/websockets/server-handshake.o

# target to build an object file
libs/websockets/server-handshake.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/server-handshake.c.o
.PHONY : libs/websockets/server-handshake.c.o

libs/websockets/server-handshake.i: libs/websockets/server-handshake.c.i
.PHONY : libs/websockets/server-handshake.i

# target to preprocess a source file
libs/websockets/server-handshake.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/server-handshake.c.i
.PHONY : libs/websockets/server-handshake.c.i

libs/websockets/server-handshake.s: libs/websockets/server-handshake.c.s
.PHONY : libs/websockets/server-handshake.s

# target to generate assembly for a file
libs/websockets/server-handshake.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/server-handshake.c.s
.PHONY : libs/websockets/server-handshake.c.s

libs/websockets/server.o: libs/websockets/server.c.o
.PHONY : libs/websockets/server.o

# target to build an object file
libs/websockets/server.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/server.c.o
.PHONY : libs/websockets/server.c.o

libs/websockets/server.i: libs/websockets/server.c.i
.PHONY : libs/websockets/server.i

# target to preprocess a source file
libs/websockets/server.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/server.c.i
.PHONY : libs/websockets/server.c.i

libs/websockets/server.s: libs/websockets/server.c.s
.PHONY : libs/websockets/server.s

# target to generate assembly for a file
libs/websockets/server.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/server.c.s
.PHONY : libs/websockets/server.c.s

libs/websockets/sha-1.o: libs/websockets/sha-1.c.o
.PHONY : libs/websockets/sha-1.o

# target to build an object file
libs/websockets/sha-1.c.o:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/sha-1.c.o
.PHONY : libs/websockets/sha-1.c.o

libs/websockets/sha-1.i: libs/websockets/sha-1.c.i
.PHONY : libs/websockets/sha-1.i

# target to preprocess a source file
libs/websockets/sha-1.c.i:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/sha-1.c.i
.PHONY : libs/websockets/sha-1.c.i

libs/websockets/sha-1.s: libs/websockets/sha-1.c.s
.PHONY : libs/websockets/sha-1.s

# target to generate assembly for a file
libs/websockets/sha-1.c.s:
	$(MAKE) -f CMakeFiles/pilight.dir/build.make CMakeFiles/pilight.dir/libs/websockets/sha-1.c.s
.PHONY : libs/websockets/sha-1.c.s

raw.o: raw.c.o
.PHONY : raw.o

# target to build an object file
raw.c.o:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/raw.c.o
.PHONY : raw.c.o

raw.i: raw.c.i
.PHONY : raw.i

# target to preprocess a source file
raw.c.i:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/raw.c.i
.PHONY : raw.c.i

raw.s: raw.c.s
.PHONY : raw.s

# target to generate assembly for a file
raw.c.s:
	$(MAKE) -f CMakeFiles/pilight-raw.dir/build.make CMakeFiles/pilight-raw.dir/raw.c.s
.PHONY : raw.c.s

receive.o: receive.c.o
.PHONY : receive.o

# target to build an object file
receive.c.o:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/receive.c.o
.PHONY : receive.c.o

receive.i: receive.c.i
.PHONY : receive.i

# target to preprocess a source file
receive.c.i:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/receive.c.i
.PHONY : receive.c.i

receive.s: receive.c.s
.PHONY : receive.s

# target to generate assembly for a file
receive.c.s:
	$(MAKE) -f CMakeFiles/pilight-receive.dir/build.make CMakeFiles/pilight-receive.dir/receive.c.s
.PHONY : receive.c.s

send.o: send.c.o
.PHONY : send.o

# target to build an object file
send.c.o:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/send.c.o
.PHONY : send.c.o

send.i: send.c.i
.PHONY : send.i

# target to preprocess a source file
send.c.i:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/send.c.i
.PHONY : send.c.i

send.s: send.c.s
.PHONY : send.s

# target to generate assembly for a file
send.c.s:
	$(MAKE) -f CMakeFiles/pilight-send.dir/build.make CMakeFiles/pilight-send.dir/send.c.s
.PHONY : send.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... pilight"
	@echo "... pilight-control"
	@echo "... pilight-daemon"
	@echo "... pilight-debug"
	@echo "... pilight-learn"
	@echo "... pilight-raw"
	@echo "... pilight-receive"
	@echo "... pilight-send"
	@echo "... pilight_shared"
	@echo "... pilight_static"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... control.o"
	@echo "... control.i"
	@echo "... control.s"
	@echo "... daemon.o"
	@echo "... daemon.i"
	@echo "... daemon.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... learn.o"
	@echo "... learn.i"
	@echo "... learn.s"
	@echo "... libs/hardwares/gpio.o"
	@echo "... libs/hardwares/gpio.i"
	@echo "... libs/hardwares/gpio.s"
	@echo "... libs/hardwares/module.o"
	@echo "... libs/hardwares/module.i"
	@echo "... libs/hardwares/module.s"
	@echo "... libs/hardwares/none.o"
	@echo "... libs/hardwares/none.i"
	@echo "... libs/hardwares/none.s"
	@echo "... libs/pilight/binary.o"
	@echo "... libs/pilight/binary.i"
	@echo "... libs/pilight/binary.s"
	@echo "... libs/pilight/config.o"
	@echo "... libs/pilight/config.i"
	@echo "... libs/pilight/config.s"
	@echo "... libs/pilight/fcache.o"
	@echo "... libs/pilight/fcache.i"
	@echo "... libs/pilight/fcache.s"
	@echo "... libs/pilight/gc.o"
	@echo "... libs/pilight/gc.i"
	@echo "... libs/pilight/gc.s"
	@echo "... libs/pilight/hardware.o"
	@echo "... libs/pilight/hardware.i"
	@echo "... libs/pilight/hardware.s"
	@echo "... libs/pilight/irq.o"
	@echo "... libs/pilight/irq.i"
	@echo "... libs/pilight/irq.s"
	@echo "... libs/pilight/json.o"
	@echo "... libs/pilight/json.i"
	@echo "... libs/pilight/json.s"
	@echo "... libs/pilight/log.o"
	@echo "... libs/pilight/log.i"
	@echo "... libs/pilight/log.s"
	@echo "... libs/pilight/options.o"
	@echo "... libs/pilight/options.i"
	@echo "... libs/pilight/options.s"
	@echo "... libs/pilight/protocol.o"
	@echo "... libs/pilight/protocol.i"
	@echo "... libs/pilight/protocol.s"
	@echo "... libs/pilight/settings.o"
	@echo "... libs/pilight/settings.i"
	@echo "... libs/pilight/settings.s"
	@echo "... libs/pilight/socket.o"
	@echo "... libs/pilight/socket.i"
	@echo "... libs/pilight/socket.s"
	@echo "... libs/pilight/threads.o"
	@echo "... libs/pilight/threads.i"
	@echo "... libs/pilight/threads.s"
	@echo "... libs/pilight/webserver.o"
	@echo "... libs/pilight/webserver.i"
	@echo "... libs/pilight/webserver.s"
	@echo "... libs/pilight/wiringPi.o"
	@echo "... libs/pilight/wiringPi.i"
	@echo "... libs/pilight/wiringPi.s"
	@echo "... libs/protocols/alecto.o"
	@echo "... libs/protocols/alecto.i"
	@echo "... libs/protocols/alecto.s"
	@echo "... libs/protocols/arctech_dimmer.o"
	@echo "... libs/protocols/arctech_dimmer.i"
	@echo "... libs/protocols/arctech_dimmer.s"
	@echo "... libs/protocols/arctech_old.o"
	@echo "... libs/protocols/arctech_old.i"
	@echo "... libs/protocols/arctech_old.s"
	@echo "... libs/protocols/arctech_switch.o"
	@echo "... libs/protocols/arctech_switch.i"
	@echo "... libs/protocols/arctech_switch.s"
	@echo "... libs/protocols/ds18b20.o"
	@echo "... libs/protocols/ds18b20.i"
	@echo "... libs/protocols/ds18b20.s"
	@echo "... libs/protocols/generic_dimmer.o"
	@echo "... libs/protocols/generic_dimmer.i"
	@echo "... libs/protocols/generic_dimmer.s"
	@echo "... libs/protocols/generic_switch.o"
	@echo "... libs/protocols/generic_switch.i"
	@echo "... libs/protocols/generic_switch.s"
	@echo "... libs/protocols/generic_weather.o"
	@echo "... libs/protocols/generic_weather.i"
	@echo "... libs/protocols/generic_weather.s"
	@echo "... libs/protocols/home_easy_old.o"
	@echo "... libs/protocols/home_easy_old.i"
	@echo "... libs/protocols/home_easy_old.s"
	@echo "... libs/protocols/impuls.o"
	@echo "... libs/protocols/impuls.i"
	@echo "... libs/protocols/impuls.s"
	@echo "... libs/protocols/raw.o"
	@echo "... libs/protocols/raw.i"
	@echo "... libs/protocols/raw.s"
	@echo "... libs/protocols/relay.o"
	@echo "... libs/protocols/relay.i"
	@echo "... libs/protocols/relay.s"
	@echo "... libs/protocols/sartano.o"
	@echo "... libs/protocols/sartano.i"
	@echo "... libs/protocols/sartano.s"
	@echo "... libs/websockets/base64-decode.o"
	@echo "... libs/websockets/base64-decode.i"
	@echo "... libs/websockets/base64-decode.s"
	@echo "... libs/websockets/daemonize.o"
	@echo "... libs/websockets/daemonize.i"
	@echo "... libs/websockets/daemonize.s"
	@echo "... libs/websockets/getifaddrs.o"
	@echo "... libs/websockets/getifaddrs.i"
	@echo "... libs/websockets/getifaddrs.s"
	@echo "... libs/websockets/handshake.o"
	@echo "... libs/websockets/handshake.i"
	@echo "... libs/websockets/handshake.s"
	@echo "... libs/websockets/libwebsockets.o"
	@echo "... libs/websockets/libwebsockets.i"
	@echo "... libs/websockets/libwebsockets.s"
	@echo "... libs/websockets/output.o"
	@echo "... libs/websockets/output.i"
	@echo "... libs/websockets/output.s"
	@echo "... libs/websockets/parsers.o"
	@echo "... libs/websockets/parsers.i"
	@echo "... libs/websockets/parsers.s"
	@echo "... libs/websockets/server-handshake.o"
	@echo "... libs/websockets/server-handshake.i"
	@echo "... libs/websockets/server-handshake.s"
	@echo "... libs/websockets/server.o"
	@echo "... libs/websockets/server.i"
	@echo "... libs/websockets/server.s"
	@echo "... libs/websockets/sha-1.o"
	@echo "... libs/websockets/sha-1.i"
	@echo "... libs/websockets/sha-1.s"
	@echo "... raw.o"
	@echo "... raw.i"
	@echo "... raw.s"
	@echo "... receive.o"
	@echo "... receive.i"
	@echo "... receive.s"
	@echo "... send.o"
	@echo "... send.i"
	@echo "... send.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

