GCC = $(CROSS_COMPILE)gcc
SYS := $(shell $(GCC) -dumpmachine)
ifdef CROSS_COMPILE
	INCLUDE = -isystem/usr/include/ -isystem/usr/include/x86_64-linux-gnu/
endif
ifneq (, $(findstring x86_64, $(SYS)))
	OSFLAGS = -Ofast -fPIC -march=native -mtune=native -mfpmath=sse -Wconversion -Wunreachable-code -Wstrict-prototypes 
endif
ifneq (, $(findstring arm, $(SYS)))
	ifneq (, $(findstring gnueabihf, $(SYS)))
		OSFLAGS = -Ofast -mfloat-abi=hard -mfpu=vfp -march=armv6 -Wconversion -Wunreachable-code -Wstrict-prototypes 
	endif
	ifneq (, $(findstring gnueabi, $(SYS)))
		OSFLAGS = -Ofast -mfloat-abi=hard -mfpu=vfp -march=armv6 -Wconversion -Wunreachable-code -Wstrict-prototypes 
	endif	
	ifneq (, $(findstring gnueabisf, $(SYS)))
		OSFLAGS = -Ofast -mfloat-abi=soft -mfpu=vfp -march=armv6 -Wconversion -Wunreachable-code -Wstrict-prototypes 
	endif
endif
ifneq (, $(findstring amd64, $(SYS)))
	OSFLAGS = -O3 -fPIC -march=native -mtune=native -mfpmath=sse -Wno-conversion
endif
GIT_HASH := $(shell git describe --always)
CFLAGS = -ffast-math $(OSFLAGS) -Wfloat-equal -Wshadow -Wpointer-arith -Wcast-align -Wstrict-overflow=5 -Wwrite-strings -Waggregate-return -Wcast-qual -Wswitch-default -Wswitch-enum -Wformat=2 -g -Wall -I. -isystem.. -Ilibs/pilight/ -Ilibs/protocols/ -Ilibs/hardware/ -Ilibs/avrdude/ -pthread -lm -DHASH=\"$(GIT_HASH)\"
SUBDIRS = libs/pilight libs/protocols libs/hardware libs/avrdude
SRC = $(wildcard *.c)
INCLUDES = $(wildcard protocols/*.h) $(wildcard protocols/*.c) $(wildcard hardware/*.h) $(wildcard hardware/*.c) $(wildcard libs/pilight/*.h) $(wildcard libs/pilight/*.c) $(wildcard libs/avrdude/*.h) $(wildcard libs/avrdude/*.c)
PROGAMS = $(patsubst %.c,pilight-%,$(SRC))
LIBS = libs/pilight/pilight.o libs/protocols/protocols.o libs/hardware/hardware.o libs/avrdude/avrdude.o
WEBFILES := $(shell cd web && find * -type f)
WEBDIRS := $(shell cd web && find * -type d )

.PHONY: subdirs $(SUBDIRS)

subdirs: $(SUBDIRS) all

$(SUBDIRS):
	$(MAKE) -C $@ GIT_HASH=$(GIT_HASH)

all: $(LIBS) libpilight.so libpilight.a $(PROGAMS) 

libpilight.so: $(LIBS)
	$(GCC) $(LIBS) -shared -o libpilight.so -lpthread -lm
	
libpilight.a: $(LIBS)
	$(CROSS_COMPILE)ar -rsc libpilight.a $(LIBS)

pilight-daemon: daemon.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

pilight-send: send.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

pilight-receive: receive.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

pilight-debug: debug.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

pilight-learn: learn.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

pilight-control: control.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

pilight-raw: raw.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so
	
pilight-uuid: uuid.c $(INCLUDES) $(LIBS) libpilight.so
	$(GCC) $(CFLAGS) -o $@ $(patsubst pilight-%,%.c,$@) libpilight.so /usr/lib/arm-linux-gnueabihf/libz.so

install:
	[ -d /usr/share/images/pilight/ ] && rm -r /usr/share/images/pilight/ || true
	
	install -m 0755 -d /usr/local/lib/pilight/
	install -m 0755 -d /usr/local/sbin
	install -m 0755 -d /etc/pilight
	for f in $(WEBDIRS) ; do \
		install -m 0755 -d /usr/local/share/pilight/$$f; \
	done
	install -m 0655 pilight-daemon /usr/local/sbin/
	install -m 0655 pilight-send /usr/local/sbin/
	install -m 0655 pilight-receive /usr/local/sbin/
	install -m 0655 pilight-control /usr/local/sbin/
	install -m 0655 pilight-debug /usr/local/sbin/
	install -m 0655 pilight-learn /usr/local/sbin/
	install -m 0655 pilight-raw /usr/local/sbin/
	install -m 0655 pilight-uuid /usr/local/sbin/
	install -m 0655 libpilight.so /usr/local/lib/pilight/
	install -m 0655 libpilight.a /usr/local/lib/pilight/
	install -m 0644 settings.json-default /etc/pilight/
	for f in $(WEBFILES) ; do \
		cd web/ && install -D $$f /usr/local/share/pilight/`dirname $$f` || true && cd ..; \
	done
	install -m 0755 init/pilight /etc/init.d/
	update-rc.d pilight defaults

	[ ! -f /etc/pilight/settings.json ] && mv /etc/pilight/settings.json-default /etc/pilight/settings.json || true
	[ ! -f /etc/pilight/hardware.json ] && cp hardware.json /etc/pilight/ || true

	mv /usr/local/lib/pilight/libpilight.so /usr/local/lib/pilight/libpilight.so.3
	ln -sf /usr/local/lib/pilight/libpilight.so.3 /usr/local/lib/libpilight.so
	ldconfig
	
clean:
	rm pilight-* >/dev/null 2>&1 || true
	rm *pilight*.so* >/dev/null 2>&1 || true
	rm *pilight*.a* >/dev/null 2>&1 || true
	$(MAKE) -C libs/protocols/ $@;
	
dist-clean:
	rm pilight-* >/dev/null 2>&1 || true
	rm *pilight*.so* >/dev/null 2>&1 || true
	rm *pilight*.a* >/dev/null 2>&1 || true
	for dir in $(SUBDIRS); do \
		$(MAKE) -C $$dir $@; \
	done
