.TH pilight-uuid 1 "10 July 2017" "7.0-dev" "pilight 7.0-dev"
.SH NAME
pilight-uuid \- Show pilight adhoc node UUID
.SH SYNOPSIS
.B pilight-uuid
.SH DESCRIPTION
.B pilight-uuid
is a tool to show the UUID for a pilight adhoc network node in order to
identify as a unique node. This prevents multiple nodes from interfering with 
each other when sending and receiving.
.PP
Prints the UUID to STDOUT.
.PP
.SH OPTIONS
.TP
\fB\-H\fR, \fB\-\-help\fR
Print allowed options and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit
.PP
.SH BUGS
Please report all bugs on GitHub <https://github.com/pilight/pilight/>.
.SH AUTHOR
.PP
Curlymo <info@pilight.org>
and contributors.
.PP
This man page was originally written by
pilino1234 <pilino1234@zoho.eu>.
.SH WWW
https://www.pilight.org/
.SH SEE ALSO
.B pilight-control(1)
.br
.B pilight-daemon(1)
.br
.B pilight-debug(1)
.br
.B pilight-flash(1)
.br
.B pilight-raw(1)
.br
.B pilight-receive(1)
.br
.B pilight-send(1)
.br
.B pilight-sha256(1)
