#!/bin/bash

if [[ $1 == "purge" ]]; then

	test -d /etc/pilight && rm -r /etc/pilight 1>/dev/null 2>/dev/null || true;

	find /usr/local/lib -name '*pilight*' -exec rm -r {} \; 1>/dev/null 2>/dev/null;

	test -d /usr/local/pilight && rm -r /usr/local/pilight || true 1>/dev/null 2>/dev/null;

fi

if [[ $1 == "remove" ]]; then

	test -f /etc/init.d/pilight && rm /etc/init.d/pilight || true;
	test -f /etc/init.d/pilight.sh && rm /etc/init.d/pilight.sh || true;
	test -f /etc/systemd/system/pilight.service && rm /etc/systemd/system/pilight.service || true;
	test -f /etc/init/pilight.conf && rm /etc/init/pilight.conf || true;

fi
