#!/bin/bash

if [[ $1 == "purge" ]]; then

	test -d /etc/pilight && rm -r /etc/pilight 1>/dev/null 2>/dev/null || true;

	find /usr/local/lib -name '*pilight*' -exec rm -r {} \; 1>/dev/null 2>/dev/null;

	test -d /usr/local/pilight && rm -r /usr/local/pilight || true 1>/dev/null 2>/dev/null;

fi