#!/bin/bash

if [[ $1 == "purge" ]]; then

	if [ -d /etc/pilight  ]; then
		rm -r /etc/pilight 1>/dev/null 2>/dev/null;
	fi
	
	if [ -d /usr/local/lib/pilight  ]; then
		rm -r /usr/local/lib/pilight 1>/dev/null 2>/dev/null;
	fi
	
	if [ -d /usr/local/share/pilight  ]; then
		rm -r /usr/local/share/pilight 1>/dev/null 2>/dev/null;
	fi	

fi