#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	if [ -L /usr/local/lib/libpilight.so.2.1 ]; then
		rm /usr/local/lib/libpilight.so.2.1 1>/dev/null 2>/dev/null; 
	fi

	if [ -d /usr/local/share/pilight/ ]; then
		rm -rf /usr/local/share/pilight
	fi
	
	if [ ! -d /usr/local/share/pilight ]; then
		mkdir -p /usr/local/share/pilight/default 1>/dev/null 2>/dev/null;
	fi

	if [ ! -d /usr/local/lib/pilight ]; then
		mkdir -p /usr/local/lib/pilight 1>/dev/null 2>/dev/null;
	fi

	if [ ! -d /etc/pilight ]; then
		mkdir -p /etc/pilight 1>/dev/null 2>/dev/null;
	fi

	if [ ! -f /usr/local/lib/pilight/libpilight.so.3.0 ]; then
		touch /usr/local/lib/pilight/libpilight.so.3.0 1>/dev/null 2>/dev/null; 
	fi
	
	if [ -L /usr/local/lib/libpilight.so ]; then
		rm /usr/local/lib/libpilight.so 1>/dev/null 2>/dev/null;
	fi
	
	if [ -f /usr/local/lib/pilight/libpilight.so.2.1 ]; then
		rm /usr/local/lib/pilight/libpilight.so.2.1 1>/dev/null 2>/dev/null;
	fi
	
	ln -sf /usr/local/lib/pilight/libpilight.so.3.0 /usr/local/lib/libpilight.so 1>/dev/null 2>/dev/null;
	rm /usr/local/lib/pilight/libpilight.so.3.0 1>/dev/null 2>/dev/null;
	
	if [ -f /etc/pilight/settings.json ]; then
		mv --backup=t /etc/pilight/settings.json /etc/pilight/settings.json.bak
	fi
	
	if [ -f /etc/pilight/hardware.json ]; then
		mv --backup=t /etc/pilight/hardware.json /etc/pilight/hardware.json.bak
	fi	
fi