#!/bin/bash

if [[ $1 == "remove" || $1 == "purge" ]]; then

	if [ -d /usr/local/lib/pilight ]; then
		rm -r /usr/local/lib/pilight 1>/dev/null 2>/dev/null;
	fi
	
	if [ -d /usr/local/share/pilight ]; then
		rm -r /usr/local/share/pilight 1>/dev/null 2>/dev/null;
	fi

	if [ -f /etc/init.d/pilight ]; then
		rm -r /etc/init.d/pilight 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-daemon ]; then
		rm -r /usr/local/sbin/pilight-daemon 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-raw ]; then
		rm -r /usr/local/sbin/pilight-raw 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-send ]; then
		rm -r /usr/local/sbin/pilight-send 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-control ]; then
		rm -r /usr/local/sbin/pilight-control 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-learn ]; then
		rm -r /usr/local/sbin/pilight-learn 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-receive ]; then
		rm -r /usr/local/sbin/pilight-receive 1>/dev/null 2>/dev/null;
	fi

	if [ -f /usr/local/sbin/pilight-debug  ]; then
		rm -r /usr/local/sbin/pilight-debug 1>/dev/null 2>/dev/null;
	fi
	
	if [ -f /usr/local/sbin/pilight-uuid  ]; then
		rm -r /usr/local/sbin/pilight-uuid 1>/dev/null 2>/dev/null;
	fi	
	
	update-rc.d pilight remove 1>/dev/null 2>/dev/null;

	if [ -L /usr/local/lib/libpilight.so ]; then
		rm /usr/local/lib/libpilight.so 1>/dev/null 2>/dev/null;
	fi	
	
fi
	